export const EXPENSE_ACTION_TYPES = {
  // GET operations
  GET_EXPENSES_START: 'expense/GET_EXPENSES_START',
  GET_EXPENSES_SUCCESS: 'expense/GET_EXPENSES_SUCCESS',
  GET_EXPENSES_FAILURE: 'expense/GET_EXPENSES_FAILURE',
  
  GET_EXPENSE_BY_ID_START: 'expense/GET_EXPENSE_BY_ID_START',
  GET_EXPENSE_BY_ID_SUCCESS: 'expense/GET_EXPENSE_BY_ID_SUCCESS',
  GET_EXPENSE_BY_ID_FAILURE: 'expense/GET_EXPENSE_BY_ID_FAILURE',
  
  GET_TOTAL_EXPENSES_START: 'expense/GET_TOTAL_EXPENSES_START',
  GET_TOTAL_EXPENSES_SUCCESS: 'expense/GET_TOTAL_EXPENSES_SUCCESS',
  GET_TOTAL_EXPENSES_FAILURE: 'expense/GET_TOTAL_EXPENSES_FAILURE',
  
  // ADD operations
  ADD_EXPENSE_START: 'expense/ADD_EXPENSE_START',
  ADD_EXPENSE_SUCCESS: 'expense/ADD_EXPENSE_SUCCESS',
  ADD_EXPENSE_FAILURE: 'expense/ADD_EXPENSE_FAILURE',
  
  // UPDATE operations
  UPDATE_EXPENSE_START: 'expense/UPDATE_EXPENSE_START',
  UPDATE_EXPENSE_SUCCESS: 'expense/UPDATE_EXPENSE_SUCCESS',
  UPDATE_EXPENSE_FAILURE: 'expense/UPDATE_EXPENSE_FAILURE',
  
  // DELETE operations
  DELETE_EXPENSE_START: 'expense/DELETE_EXPENSE_START',
  DELETE_EXPENSE_SUCCESS: 'expense/DELETE_EXPENSE_SUCCESS',
  DELETE_EXPENSE_FAILURE: 'expense/DELETE_EXPENSE_FAILURE',
  
  // Receipt operations
  UPLOAD_EXPENSE_RECEIPTS_START: 'expense/UPLOAD_EXPENSE_RECEIPTS_START',
  UPLOAD_EXPENSE_RECEIPTS_SUCCESS: 'expense/UPLOAD_EXPENSE_RECEIPTS_SUCCESS',
  UPLOAD_EXPENSE_RECEIPTS_FAILURE: 'expense/UPLOAD_EXPENSE_RECEIPTS_FAILURE',
  
  GET_EXPENSE_RECEIPTS_START: 'expense/GET_EXPENSE_RECEIPTS_START',
  GET_EXPENSE_RECEIPTS_SUCCESS: 'expense/GET_EXPENSE_RECEIPTS_SUCCESS',
  GET_EXPENSE_RECEIPTS_FAILURE: 'expense/GET_EXPENSE_RECEIPTS_FAILURE',
  
  DELETE_EXPENSE_RECEIPT_START: 'expense/DELETE_EXPENSE_RECEIPT_START',
  DELETE_EXPENSE_RECEIPT_SUCCESS: 'expense/DELETE_EXPENSE_RECEIPT_SUCCESS',
  DELETE_EXPENSE_RECEIPT_FAILURE: 'expense/DELETE_EXPENSE_RECEIPT_FAILURE',
  
  // State management
  SET_SELECTED_EXPENSE: 'expense/SET_SELECTED_EXPENSE',
  SET_EXPENSE_FIELD: 'expense/SET_EXPENSE_FIELD',
  RESET_EXPENSE_STATE: 'expense/RESET_EXPENSE_STATE'
};

