import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { IconType } from "react-icons";
import FeatureHeroMock from "@/components/Marketing/FeatureHeroMock";
import MaintenanceTrackingFeatureSection from "@/components/Marketing/MaintenanceTrackingFeatureSection";
import RentCollectionHeroMock from "@/components/Marketing/RentCollectionHeroMock";
import StructuredData from "@/components/SEO/StructuredData";
import { applyOttoSeo } from "@/lib/otto-seo";
import { webPageSchema } from "@/lib/structured-data";
import {
  FiLayout,
  FiFileText,
  FiFile,
  FiCreditCard,
  FiZap,
  FiHome,
  FiTool,
  FiDollarSign,
  FiBarChart2,
  FiBell,
  FiFolder,
  FiRefreshCw,
  FiCheck,
  FiArrowLeft,
  FiShield,
  FiX,
  FiGlobe,
  FiBookOpen,
  FiMessageSquare,
  FiAlertTriangle,
  FiActivity,
  FiTrendingUp,
  FiMapPin,
} from "react-icons/fi";

const featureDetails: Record<string, {
  icon: IconType;
  title: string;
  shortDescription: string;
  description: string;
  benefits: string[];
  features: string[];
  seoKeywords: string;
}> = {
  'ai-summaries': {
    icon: FiActivity,
    title: 'Percy AI Summaries',
    shortDescription: 'Instant plain-English summaries of your entire portfolio — rent collection, maintenance, leases, and tenant activity — generated by Percy.',
    description: 'Stop piecing together the full picture from scattered reports and inboxes. Percy AI Summaries gives you a clear, plain-English overview of everything happening across your portfolio — who has paid, what maintenance is open, which leases are expiring, and more — all in seconds. Included with Premium.',
    benefits: [
      'Instant portfolio-wide snapshot in plain English',
      'Rent collection status at a glance',
      'Open maintenance request highlights',
      'Lease expiration awareness without digging',
      'Tenant activity summaries',
      'Saves time vs. manually reviewing every report'
    ],
    features: [
      'Percy-generated portfolio summaries',
      'Rent, maintenance, lease, and tenant coverage',
      'Automatically updated with latest data',
      'Plain-English output — no jargon',
      'Accessible from your dashboard',
      'Included in Premium at no extra cost'
    ],
    seoKeywords: 'AI property management summaries, landlord AI insights, rental portfolio AI, property management AI tools'
  },
  'rent-estimate': {
    icon: FiTrendingUp,
    title: 'Rent Estimates',
    shortDescription: 'Know exactly what your unit is worth before you list it. Get instant, data-driven rent estimates based on real comparable listings in your area.',
    description: 'Stop guessing and start pricing with confidence. Rent Estimates pulls real comparable listings near your property and surfaces a data-driven rent range so you can list at the right price — maximizing income without sitting vacant. Included with Premium.',
    benefits: [
      'Instant market rent analysis for your address',
      'Comparable listings from your area',
      'Avoid underpricing that costs you monthly',
      'Avoid overpricing that leaves units empty',
      'Price confidently before every listing',
      'Included with Premium — no extra cost'
    ],
    features: [
      'Address-based rent range estimates',
      'Real comparable rental listings',
      'Market data updated regularly',
      'Available per unit inside your dashboard',
      'Works for any property type',
      'Included in Premium at no extra cost'
    ],
    seoKeywords: 'rent estimate tool, rental price estimate, market rent analysis, landlord rent pricing, comparable rent listings'
  },
  'all-in-one-dashboard': {
    icon: FiLayout,
    title: 'All-in-One Dashboard',
    shortDescription: 'Get a complete real-time overview of your properties, tenants, leases, and finances in one centralized dashboard.',
    description: 'Our comprehensive dashboard provides you with a real-time view of your entire property management operation powered by SignalR. See updates instantly without refreshing—no more switching between multiple apps or spreadsheets. Unlike bloated property management software like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant, our dashboard focuses on what matters most to solo landlords and growing portfolios.',
    benefits: [
      'Real-time property performance metrics',
      'Instant updates without page refresh',
      'Quick access to all tenant information',
      'Financial overview with key indicators',
      'Maintenance request status at a glance',
      'Lease expiration alerts and reminders'
    ],
    features: [
      'SignalR-powered real-time updates',
      'Interactive charts and graphs',
      'Quick action buttons for common tasks',
      'Notification center with live updates',
      'Global search functionality',
      'Export capabilities for reports'
    ],
    seoKeywords: 'property management dashboard, landlord dashboard, real-time property management, property management overview'
  },
  'property-management': {
    icon: FiHome,
    title: 'Property Management',
    shortDescription: 'Easily manage multiple properties with detailed records, photos, and documents.',
    description: 'Streamline your property management with comprehensive tools designed to handle everything from single units to large portfolios. Track property performance, maintenance history, and financial data all in one place. Perfect for solo landlords who need powerful tools without the complexity of enterprise solutions like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant.',
    benefits: [
      'Centralized property database',
      'Photo and document storage',
      'Property performance tracking',
      'Maintenance history records',
      'Financial tracking per property',
      'Tenant assignment and management'
    ],
    features: [
      'Property details and specifications',
      'Photo galleries and virtual tours',
      'Document management system',
      'Property value tracking',
      'Expense categorization',
      'Rental income tracking'
    ],
    seoKeywords: 'property management software, rental property management, property portfolio management, landlord property tracking'
  },
  'lease-management': {
    icon: FiFile,
    title: 'Digital Lease Management & Online Signing',
    shortDescription: 'Create and sign leases digitally with DocuSign integration. Simple lease management tools built for independent landlords. Start free.',
    description: 'Simplify your lease management process with digital document creation, electronic signatures via DocuSign, and automated tracking. Send leases for signature electronically, track signing status in real-time, and never miss a renewal or expiration date. A streamlined solution compared to complex platforms like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant.',
    benefits: [
      'Digital lease creation and storage',
      'DocuSign integration for e-signatures',
      'Automated signature workflow',
      'Real-time signature status tracking',
      'Automated renewal reminders',
      'Lease term and expiration tracking'
    ],
    features: [
      'Digital lease document generation',
      'DocuSign envelope management',
      'Electronic signature workflow',
      'Lease expiration alerts',
      'Renewal management',
      'Signed document storage'
    ],
    seoKeywords: 'digital lease signing, DocuSign property management, electronic lease signing, lease management software'
  },
  'maintenance-tracking': {
    icon: FiTool,
    title: 'Maintenance Tracking',
    shortDescription: 'Turn tenant repair requests into organized work orders with clear status tracking, photo documentation, vendor notes, and property-by-property maintenance history. Property Peace helps independent landlords stay ahead of repairs without scattered texts, forgotten calls, or spreadsheet follow-up.',
    description: 'Efficiently manage all maintenance requests and work orders from creation to completion. Track vendor relationships, schedule repairs, and maintain detailed maintenance history. A focused solution for landlords who need maintenance tracking without the bloat of enterprise platforms like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant.',
    benefits: [
      'Tenant maintenance request portal',
      'Work order creation and tracking',
      'Vendor management system',
      'Maintenance history records',
      'Photo documentation of issues',
      'Cost tracking per maintenance item'
    ],
    features: [
      'Request submission and tracking',
      'Priority assignment system',
      'Vendor contact management',
      'Maintenance scheduling calendar',
      'Photo uploads for issues',
      'Cost and invoice tracking'
    ],
    seoKeywords: 'maintenance tracking software, property maintenance management, work order tracking, tenant maintenance requests'
  },
  'rent-collection': {
    icon: FiDollarSign,
    title: 'Online Rent Collection',
    shortDescription: 'Automated rent tracking with overdue calculations and multi-channel reminders.',
    description: 'Automate your rent collection process with comprehensive payment tracking, automated reminders via email and SMS, and late fee calculations. Generate rent roll reports effortlessly and stay on top of all payments. Unlike complex platforms like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant, our rent collection is straightforward and landlord-focused.',
    benefits: [
      'Automated payment tracking',
      'Overdue calculations',
      'Multi-channel payment reminders (Email/SMS)',
      'Payment history tracking',
      'Late fee calculation',
      'Rent roll report generation'
    ],
    features: [
      'Rent collection dashboard',
      'Automated reminder scheduling',
      'Payment confirmation notifications',
      'Late payment tracking',
      'Partial payment handling',
      'Export capabilities for accounting'
    ],
    seoKeywords: 'online rent collection, rent payment software, automated rent collection, rent tracking software'
  },
  'financial-reports': {
    icon: FiBarChart2,
    title: 'Financial Reporting',
    shortDescription: 'Comprehensive financial reporting with property profitability analysis and tax categorization.',
    description: 'Get detailed insights into your property finances with advanced analytics and comprehensive reporting tools. Track property profitability, generate year-over-year comparisons, prepare tax documents with categorization, and export data for accounting software. Essential financial tools without the complexity of enterprise solutions like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant.',
    benefits: [
      'Property profitability analysis',
      'Year-over-year financial comparisons',
      'Tax document generation with categorization',
      'Expense categorization by tax category',
      'Income tracking by property',
      'Export to Excel for accounting software'
    ],
    features: [
      'Property portfolio analytics',
      'Customizable report templates',
      'Date range filtering',
      'Property-specific reports',
      'Tax deductible expense tracking',
      'Excel and PDF export'
    ],
    seoKeywords: 'property financial reporting, landlord accounting software, property profitability analysis, rental property reports'
  },
  'tenant-communication': {
    icon: FiBell,
    title: 'Multi-Channel Notifications',
    shortDescription: 'Stay connected with tenants through in-app, email, and SMS notifications.',
    description: 'Never miss an important update with our multi-channel notification system. Send and receive notifications via in-app messages, email, and SMS. Customize preferences for each notification type and maintain complete communication history. Simple and effective communication tools designed for landlords, unlike complex platforms like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant.',
    benefits: [
      'In-app real-time notifications',
      'Email notifications for important events',
      'SMS alerts for critical updates',
      'Customizable notification preferences',
      'Notification history tracking',
      'Mark as read functionality'
    ],
    features: [
      'Real-time SignalR notifications',
      'Email template system',
      'SMS notification support',
      'User-configurable preferences',
      'Notification center dashboard',
      'Mobile-responsive interface'
    ],
    seoKeywords: 'tenant communication software, property management notifications, landlord tenant messaging, multi-channel notifications'
  },
  'document-management': {
    icon: FiFolder,
    title: 'Document Management',
    shortDescription: 'Store and organize all property documents securely in the cloud.',
    description: 'Keep all your property documents, leases, receipts, and tenant files organized and accessible from anywhere. Secure Azure cloud storage ensures your important documents are always available when you need them. A straightforward document management solution for landlords, without the bloat of enterprise platforms like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant.',
    benefits: [
      'Azure cloud-based document storage',
      'Organized folder structure',
      'Secure document access with time-limited tokens',
      'Document version control',
      'Easy search and retrieval',
      'Mobile document access'
    ],
    features: [
      'File upload and storage',
      'Folder organization system',
      'Document tagging and categorization',
      'Search functionality',
      'Document sharing capabilities',
      'Automatic backups'
    ],
    seoKeywords: 'property document management, cloud document storage, landlord document management, property file management'
  },
  'rental-applications': {
    icon: FiFileText,
    title: 'Rental Applications',
    shortDescription: 'Complete digital rental application workflow from invite to signed lease.',
    description: 'Revolutionize your tenant screening process with a fully digital application system. Send secure invites via email, tenants apply online with no account required, and PDFs are automatically generated—all in one seamless workflow. Streamlined application processing for landlords, unlike complex platforms like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant.',
    benefits: [
      'Email-based secure invite system',
      'One-time use secure links (14-day expiration)',
      'Tenants apply without creating accounts',
      'Automatic professional PDF generation',
      'Application status tracking',
      'Complete audit trail'
    ],
    features: [
      'Secure token-based invite links',
      'Pre-filled property/unit information',
      'Comprehensive application forms',
      'Automatic PDF generation and storage',
      'Application status workflow management',
      'Review notes and internal comments'
    ],
    seoKeywords: 'rental application software, tenant application management, digital rental applications, tenant screening software'
  },
  'payment-processing': {
    icon: FiCreditCard,
    title: 'Integrated Payment Processing',
    shortDescription: 'Accept online payments with Stripe integration and automated tracking.',
    description: 'Streamline rent collection with built-in Stripe payment processing. Accept online payments, track payment history, calculate late fees automatically, and send payment reminders—all integrated into your property management workflow. Simple payment processing designed for landlords, without the complexity of enterprise solutions like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant.',
    benefits: [
      'Stripe payment processing integration',
      'Online payment acceptance',
      'Automated payment tracking',
      'Late fee calculations',
      'Payment confirmation emails',
      'Multiple payment methods supported'
    ],
    features: [
      'Secure payment processing',
      'Payment history tracking',
      'Recurring payment setup',
      'Payment method management',
      'Automated reminders',
      'Financial reporting integration'
    ],
    seoKeywords: 'property payment processing, Stripe property management, online rent payments, property payment software'
  },
  'real-time-communication': {
    icon: FiZap,
    title: 'Real-Time Communication',
    shortDescription: 'Instant messaging with tenants powered by SignalR real-time technology.',
    description: 'Communicate with tenants instantly using our real-time messaging system powered by SignalR. Get instant notifications, see messages as they arrive, and never miss an important conversation—all without refreshing the page. Real-time communication that actually works for landlords, unlike complex platforms like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant.',
    benefits: [
      'Real-time message delivery',
      'Instant notifications',
      'No page refresh needed',
      'Message read receipts',
      'Conversation history',
      'File sharing capabilities'
    ],
    features: [
      'SignalR-powered real-time messaging',
      'Instant message notifications',
      'Conversation threads',
      'Message search functionality',
      'Attachment support',
      'Mobile-responsive interface'
    ],
    seoKeywords: 'real-time tenant communication, property management messaging, landlord tenant chat, instant property communication'
  },
  'automation': {
    icon: FiRefreshCw,
    title: 'Automated Workflows',
    shortDescription: 'Set it once and let the system work for you with automated reminders and alerts.',
    description: 'Automate repetitive tasks and never miss important deadlines. Schedule automated rent reminders, lease expiration alerts, maintenance follow-ups, and more. Spend less time on routine tasks and more time growing your business. Simple automation for landlords, without the bloat of enterprise platforms like Appfolio, Buildium, DoorLoop, Yardi Breeze, Rent Manager, TenantCloud, Entrata, Innago, MRI Software, and TurboTenant.',
    benefits: [
      'Automated rent due reminders',
      'Lease expiration alerts',
      'Scheduled maintenance follow-ups',
      'Payment confirmation notifications',
      'Application status updates',
      'Customizable notification preferences'
    ],
    features: [
      'Multi-channel notifications (Email/SMS/In-App)',
      'Scheduled background tasks',
      'Configurable notification rules',
      'Automated report generation',
      'Recurring expense tracking',
      'Overdue payment alerts'
    ],
    seoKeywords: 'property management automation, automated landlord workflows, property management reminders, rental property automation'
  },
  'lease-shield': {
    icon: FiShield,
    title: 'LeaseShield',
    shortDescription: 'Get lease and landlord-tenant law answers backed only by official government and state law sources—no guesswork, no generic AI.',
    description: "LeaseShield is the only landlord tool that answers your lease and state law questions using exclusively government and official state law sources. Every answer is grounded in your state's statutes, attorney general guides, housing agency resources, and .gov websites—so you get accurate, defensible information you can trust. No generic AI, no random blogs: just citations to the same sources lawyers and courts use. Reduce legal risk, avoid costly mistakes, and give tenants clear, legally sound answers. LeaseShield is built for landlords who want to stay compliant and confident. Try it free as part of Property Peace.",
    benefits: [
      'Answers sourced only from government and official state law sources',
      'State-specific landlord-tenant law and lease guidance',
      'Citations to statutes, .gov sites, and state housing resources',
      'Reduces legal risk with accurate, defensible information',
      'No generic AI—every answer tied to a real, citable source',
      'Helps you and your tenants understand rights and obligations'
    ],
    features: [
      'Official state law sources only (no third-party or blog content)',
      'Conversation history per lease with state context',
      'State selection so answers match your property\'s jurisdiction',
      'Clear citations and links to government sources',
      'Lease-specific Q&A so context is always in mind',
      'Included in Property Peace at no extra cost'
    ],
    seoKeywords: 'LeaseShield, lease questions government sources, state landlord tenant law, landlord lease answers, official state law sources, .gov lease information, landlord legal compliance, state housing law'
  }
};

const ottoFeatureH1Overrides: Record<string, string> = {
  'maintenance-tracking': 'Effortless Property Maintenance Tracking for Landlords',
  'all-in-one-dashboard': 'Property Peace: The All-in-One Dashboard for Landlords',
  'property-management': 'Property Management Software for Independent Landlords',
  'document-management': 'Secure Document Management for Independent Landlords',
  'automation': 'Automate Your Property Management: Tasks Made Simple',
  'rent-estimate': 'Data-Driven Rent Estimates for Independent Landlords',
  'ai-summaries': 'Percy AI Summaries: Your Entire Property Portfolio at a Glance',
};

const ottoFeatureH2Overrides: Record<string, string> = {
  'payment-processing': 'Streamlined Rent Collection and Payment Features',
  'maintenance-tracking': 'Streamline Maintenance and Work Order Tracking',
  'all-in-one-dashboard': 'Key Features of the Property Peace Dashboard',
  'ai-summaries': 'What Percy AI Summaries Cover',
};

// Generate static params for all feature pages
export function generateStaticParams() {
  return Object.keys(featureDetails).map((slug) => ({
    slug: slug,
  }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const feature = featureDetails[slug];

  if (!feature) {
    return {
      title: 'Feature Not Found | Property Peace'
    };
  }

  const isLeaseShield = slug === 'lease-shield';
  const isLeaseManagement = slug === 'lease-management';
  const title = isLeaseManagement
    ? 'Digital Lease Signing & Management for Landlords'
    : `${feature.title} | Property Peace`;
  const description = isLeaseManagement
    ? 'Create and sign leases digitally with DocuSign integration. Simple lease management tools built for independent landlords. Start free.'
    : isLeaseShield
    ? 'LeaseShield answers lease and landlord-tenant questions with official government and state-law sources, citations, and state-specific context.'
    : `${feature.shortDescription} Built for independent landlords who want simple property management tools without enterprise bloat.`;

  return applyOttoSeo(`/features/${slug}/`, {
    title,
    description,
    keywords: `${feature.seoKeywords}, ${feature.title.toLowerCase()}, property management features, landlord software`,
    alternates: { canonical: `/features/${slug}` },
    openGraph: {
      title,
      description,
      type: 'website' as const,
      url: `https://propertypeace.io/features/${slug}`,
    },
    twitter: {
      card: 'summary_large_image' as const,
      title,
      description,
    },
  });
}

export default async function FeatureDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const feature = featureDetails[slug];

  if (!feature) {
    notFound();
  }

  const IconComponent = feature.icon;
  const siteUrl = 'https://propertypeace.io';
  const structuredData = () => (
    <>
      <StructuredData
        data={{
          '@context': 'https://schema.org',
          '@type': 'BreadcrumbList',
          itemListElement: [
            { '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl },
            { '@type': 'ListItem', position: 2, name: 'Features', item: `${siteUrl}/features` },
            { '@type': 'ListItem', position: 3, name: feature.title, item: `${siteUrl}/features/${slug}` },
          ],
        }}
      />
      <StructuredData
        data={webPageSchema({
          path: `/features/${slug}`,
          name: `Property Peace ${feature.title}`,
          description: feature.shortDescription,
        })}
      />
      <StructuredData
        data={{
          '@context': 'https://schema.org',
          '@type': 'SoftwareApplication',
          name: `Property Peace ${feature.title}`,
          applicationCategory: 'BusinessApplication',
          operatingSystem: 'Web',
          url: `${siteUrl}/features/${slug}`,
          description: feature.shortDescription,
          offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD', description: 'Built for hands-on landlords with 1–50 units. Start free; premium plans available.' },
          featureList: feature.features,
        }}
      />
    </>
  );

  const glass    = { background: '#f0fdf4', border: '1px solid #dcfce7' };
  const glassDim = { background: '#f0fdf4', border: '1px solid #dcfce7' };

  // ── shared hero + trust bar (Listings-style light bg) ─────────────────────
  const renderHero = (title: React.ReactNode, subtitle: string, badge?: string, ctaLabel?: string, trustItems?: string[]) => (
    <>
      <div className="mx-auto max-w-6xl px-4 pb-14 pt-24 sm:px-6 sm:pb-18 sm:pt-10 lg:px-8 lg:pb-20">
        <Link href="/features" className="mb-10 inline-flex items-center text-[#516A80] transition-colors hover:text-green-600" style={{ fontFamily: '"Inter", sans-serif' }}>
          <FiArrowLeft className="mr-2 h-4 w-4" />Back to Features
        </Link>
        <div className="grid items-center gap-10 lg:grid-cols-[minmax(0,0.95fr)_minmax(420px,1.05fr)] lg:gap-12">
          <div className="text-center lg:text-left">
            {badge && (
              <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-green-500/20 bg-green-50 px-3.5 py-2 text-xs font-semibold uppercase leading-snug tracking-widest text-green-600 shadow-sm sm:px-4" style={{ fontFamily: '"Inter", sans-serif' }}>
                {badge}
              </div>
            )}
            <h1 className="mb-5 text-[2.3rem] font-bold leading-[1.08] text-primary-main sm:text-5xl md:text-6xl" style={{ fontFamily: '"Poppins", sans-serif' }}>{title}</h1>
            <p className="mx-auto mb-7 max-w-2xl text-[17px] leading-relaxed text-[#737373] md:text-xl lg:mx-0" style={{ fontFamily: '"Inter", sans-serif' }}>{subtitle}</p>
            <div className="mx-auto grid max-w-[22rem] grid-cols-2 justify-center gap-2.5 sm:flex sm:max-w-none sm:flex-row sm:justify-center sm:gap-3 lg:mx-0 lg:justify-start">
              <Link href="https://app.propertypeace.io/register" className="inline-flex min-h-[50px] items-center justify-center gap-2 rounded-none bg-gradient-to-r from-green-500 to-green-600 px-4 py-3 text-sm font-semibold text-white shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:from-green-600 hover:to-green-700 sm:min-h-[56px] rounded-none sm:px-8 sm:text-base" style={{ fontFamily: '"Inter", sans-serif' }}>
                <FiZap className="h-4 w-4" />{ctaLabel ?? 'Get Started Free'}
              </Link>
              <Link href="/pricing" className="inline-flex min-h-[50px] items-center justify-center gap-2 rounded-none border border-[#E5E5E5] bg-white px-4 py-3 text-sm font-semibold text-primary-main shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:border-green-300 hover:text-green-600 sm:min-h-[56px] rounded-none sm:px-8 sm:text-base" style={{ fontFamily: '"Inter", sans-serif' }}>
                View Pricing
              </Link>
            </div>
            {(trustItems ?? []).length > 0 && (
              <div className="mt-5 grid grid-cols-2 gap-2 text-[13px] font-semibold text-primary-main sm:flex sm:flex-wrap lg:justify-start" style={{ fontFamily: '"Inter", sans-serif' }}>
                {(trustItems ?? []).slice(0, 4).map((t) => (
                  <span key={t} className="inline-flex min-h-[40px] items-center justify-center gap-2 rounded-2xl border border-[#E5E5E5] bg-white px-3 py-2 leading-snug shadow-sm sm:min-h-0 sm:rounded-full sm:py-1"><FiCheck className="h-4 w-4 flex-shrink-0 text-green-600" />{t}</span>
                ))}
              </div>
            )}
          </div>

          <FeatureHeroMock slug={slug} title={typeof title === 'string' ? title : feature.title} benefits={(trustItems ?? feature.benefits).slice(0, 4)} />
        </div>
      </div>
    </>
  );

  const renderMaintenanceTrackingHero = () => {
    const trustItems = feature.benefits.slice(0, 2);

    return (
      <div className="relative overflow-hidden bg-[#061E35]">
        <div
          className="absolute inset-0 bg-cover bg-center bg-no-repeat"
          style={{ backgroundImage: 'url(/images/landing/maintenance-tracking-hero.jpg)' }}
          aria-hidden="true"
        />
        <div className="absolute inset-0 bg-[#061E35]/68" aria-hidden="true" />
        <div className="absolute inset-y-0 left-0 w-full bg-gradient-to-r from-[#061E35]/85 via-[#061E35]/58 to-[#061E35]/28" aria-hidden="true" />
        <div className="relative mx-auto flex min-h-[560px] max-w-6xl flex-col justify-center px-4 pb-16 pt-28 text-center sm:min-h-[620px] sm:px-6 sm:pb-20 sm:pt-24 lg:min-h-[700px] lg:px-8 lg:py-24">
          <div className="mx-auto max-w-4xl">
            <h1 className="mb-5 text-[2.3rem] font-bold leading-[1.08] text-white sm:text-5xl md:text-6xl" style={{ fontFamily: '"Poppins", sans-serif' }}>
              Maintenance Tracking for <span className="text-green-400">Landlords</span>
            </h1>
            <p className="mx-auto mb-7 max-w-3xl text-[17px] leading-relaxed text-white/90 md:text-xl" style={{ fontFamily: '"Inter", sans-serif' }}>
              {feature.shortDescription}
            </p>

            <div className="mx-auto grid max-w-[22rem] grid-cols-2 justify-center gap-2.5 sm:flex sm:max-w-none sm:flex-row sm:justify-center sm:gap-3">
              <Link href="https://app.propertypeace.io/register" className="inline-flex min-h-[50px] items-center justify-center gap-2 rounded-none bg-gradient-to-r from-green-500 to-green-600 px-4 py-3 text-sm font-semibold text-white shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:from-green-600 hover:to-green-700 sm:min-h-[56px] sm:px-8 sm:text-base" style={{ fontFamily: '"Inter", sans-serif' }}>
                <FiZap className="h-4 w-4" />Get Started Free
              </Link>
              <Link href="/pricing" className="inline-flex min-h-[50px] items-center justify-center gap-2 rounded-none border border-white/60 bg-white/10 px-4 py-3 text-sm font-semibold text-white shadow-sm backdrop-blur-sm transition-all duration-300 hover:-translate-y-0.5 hover:bg-white/20 sm:min-h-[56px] sm:px-8 sm:text-base" style={{ fontFamily: '"Inter", sans-serif' }}>
                View Pricing
              </Link>
            </div>

            <div className="mt-5 flex flex-wrap justify-center gap-2 text-[13px] font-semibold text-white/90" style={{ fontFamily: '"Inter", sans-serif' }}>
              {trustItems.map((item) => (
                <span key={item} className="inline-flex min-h-[38px] items-center justify-center gap-2 rounded-full border border-white/25 bg-white/15 px-3 py-1.5 leading-snug shadow-sm backdrop-blur-sm">
                  <FiCheck className="h-4 w-4 flex-shrink-0 text-green-400" />{item}
                </span>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  };

  // ── before/after comparison cards ────────────────────────────────────────
  const renderBeforeAfter = (label: string, without: string[], withItems: string[], icon: React.ReactNode) => (
    <div className="grid md:grid-cols-2 gap-6">
      <div className="rounded-2xl p-8" style={{ background: 'rgba(239,68,68,0.05)', border: '1px solid rgba(239,68,68,0.15)' }}>
        <div className="flex items-center gap-3 mb-6">
          <div className="w-9 h-9 rounded-full flex items-center justify-center flex-shrink-0" style={{ background: 'rgba(239,68,68,0.1)' }}>
            <FiAlertTriangle className="w-5 h-5 text-red-500" />
          </div>
          <h3 className="text-lg font-bold text-primary-main" style={{ fontFamily: '"Poppins", sans-serif' }}>Without {label}</h3>
        </div>
        <ul className="space-y-3">
          {without.map((item) => (
            <li key={item} className="flex items-start gap-3 text-sm text-[#516A80]" style={{ fontFamily: '"Inter", sans-serif' }}>
              <FiX className="w-4 h-4 text-red-400 flex-shrink-0 mt-0.5" />{item}
            </li>
          ))}
        </ul>
      </div>
      <div className="rounded-2xl p-8" style={{ background: 'rgba(34,197,94,0.06)', border: '1px solid rgba(34,197,94,0.18)' }}>
        <div className="flex items-center gap-3 mb-6">
          <div className="w-9 h-9 rounded-full flex items-center justify-center flex-shrink-0" style={{ background: 'rgba(34,197,94,0.12)' }}>
            {icon}
          </div>
          <h3 className="text-lg font-bold text-primary-main" style={{ fontFamily: '"Poppins", sans-serif' }}>With {label}</h3>
        </div>
        <ul className="space-y-3">
          {withItems.map((item) => (
            <li key={item} className="flex items-start gap-3 text-sm text-[#2d4a62]" style={{ fontFamily: '"Inter", sans-serif' }}>
              <FiCheck className="w-4 h-4 text-[#16a34a] flex-shrink-0 mt-0.5" />{item}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );

  // ── navy CTA card ─────────────────────────────────────────────────────────
  const renderCTA = (headline: string, sub: string, icon: React.ReactNode, ctaLabel: string) => (
    <div className="relative overflow-hidden rounded-2xl bg-[#061e35] p-10 text-center md:p-14" style={{ boxShadow: '0 20px 60px rgba(10,45,82,0.18)' }}>
      <div className="inline-flex items-center justify-center w-14 h-14 rounded-2xl mb-6" style={{ background: 'rgba(255,255,255,0.1)' }}>{icon}</div>
      <h2 className="text-3xl md:text-4xl font-bold text-white mb-4" style={{ fontFamily: '"Poppins", sans-serif' }}>{headline}</h2>
      <p className="text-lg text-white/70 max-w-xl mx-auto mb-8 leading-relaxed" style={{ fontFamily: '"Inter", sans-serif' }}>{sub}</p>
      <Link href="https://app.propertypeace.io/register" className="inline-flex items-center justify-center gap-2 px-10 py-4 bg-gradient-to-r from-green-500 to-green-600 text-white rounded-none font-semibold transition-all duration-300 hover:from-green-600 hover:to-green-700 hover:-translate-y-0.5 hover:shadow-[0_10px_24px_rgba(34,197,94,0.25)] shadow-lg" style={{ fontFamily: '"Inter", sans-serif' }}>
        <FiZap className="w-4 h-4" />{ctaLabel}
      </Link>
    </div>
  );

  // ── section heading ───────────────────────────────────────────────────────
  const renderSectionHeading = (children: React.ReactNode) => (
    <h2 className="text-3xl md:text-4xl font-bold text-primary-main text-center mb-12" style={{ fontFamily: '"Poppins", sans-serif' }}>{children}</h2>
  );

  // ── step cards (how-it-works) ─────────────────────────────────────────────
  const renderStepCards = (steps: { icon: React.ComponentType<{ className?: string }>; step: string; title: string; body: string }[]) => (
    <div className="grid md:grid-cols-3 gap-6">
      {steps.map(({ icon: Icon, step, title, body }) => (
        <div key={step} className="relative rounded-2xl p-8" style={glass}>
          <div className="text-5xl font-bold absolute top-6 right-6 leading-none select-none" style={{ fontFamily: '"Poppins", sans-serif', color: 'rgba(34,197,94,0.10)' }}>{step}</div>
          <div className="w-12 h-12 rounded-xl flex items-center justify-center mb-5" style={{ background: 'rgba(34,197,94,0.12)' }}>
            <Icon className="w-6 h-6 text-[#16a34a]" />
          </div>
          <h3 className="text-lg font-bold text-primary-main mb-3" style={{ fontFamily: '"Poppins", sans-serif' }}>{title}</h3>
          <p className="text-sm text-[#516A80] leading-relaxed" style={{ fontFamily: '"Inter", sans-serif' }}>{body}</p>
        </div>
      ))}
    </div>
  );

  // ── detail grid ───────────────────────────────────────────────────────────
  const renderDetailGrid = (items: { title: string; body: string }[]) => (
    <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
      {items.map(({ title, body }) => (
        <div key={title} className="rounded-2xl p-6 transition-all duration-200 hover:bg-green-50/70" style={glass}>
          <div className="mb-3 flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg flex flex-shrink-0 items-center justify-center" style={{ background: 'rgba(34,197,94,0.12)' }}>
              <FiCheck className="w-4 h-4 text-[#16a34a]" />
            </div>
            <h3 className="text-base font-bold text-primary-main" style={{ fontFamily: '"Poppins", sans-serif' }}>{title}</h3>
          </div>
          <p className="text-sm text-[#516A80] leading-relaxed" style={{ fontFamily: '"Inter", sans-serif' }}>{body}</p>
        </div>
      ))}
    </div>
  );

  // ── Percy AI Summaries ──────────────────────────────────────────────────────────
  if (slug === 'ai-summaries') {
    return (
      <>
        {structuredData()}
        <div className="relative overflow-hidden bg-white">
          <div className="absolute inset-0 pointer-events-none opacity-[0.04]" style={{ backgroundImage: 'radial-gradient(circle, #16a34a 1px, transparent 1px)', backgroundSize: '28px 28px' }} />
          <div className="relative">
            {renderHero(
              'Percy AI Summaries: Your Entire Property Portfolio at a Glance',
              'Stop piecing together the full picture. Get an instant plain-English summary of your entire portfolio — rent, maintenance, leases, and tenant activity — generated automatically.',
              'Premium Feature',
              'Try Percy AI Summaries Free',
              ['Plain-English output', 'Covers rent, maintenance & leases', 'Always up to date', 'Included with Premium']
            )}
          </div>
        </div>
        <div className="bg-white">
          <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-16">
            {renderBeforeAfter('Percy AI Summaries',
              ['Opening three different reports just to check in', 'Missing overdue rent because it got buried', 'Forgetting a lease expires next month', 'Manually cross-referencing maintenance and payments', 'Spending 20 minutes to get a 30-second answer'],
              ['One summary covers your entire portfolio', "See who has paid and who hasn't — instantly", 'Upcoming lease expirations surfaced automatically', 'Open maintenance requests called out clearly', 'Full picture in seconds, not minutes'],
              <FiActivity className="w-5 h-5 text-[#16a34a]" />
            )}
            <div>
              {renderSectionHeading('What Percy AI Summaries Cover')}
              <div className="grid md:grid-cols-3 gap-6">
                {[
                  { icon: FiDollarSign, title: 'Rent collection', body: "Who's paid, who's overdue, and which payments are coming up — all surfaced without opening a single report." },
                  { icon: FiTool, title: 'Maintenance activity', body: 'Open requests, recently resolved issues, and anything that needs your attention — highlighted automatically.' },
                  { icon: FiFile, title: 'Lease status', body: 'Upcoming expirations, recently signed leases, and renewal opportunities — so nothing slips through.' },
                ].map(({ icon: Icon, title, body }) => (
                  <div key={title} className="rounded-2xl p-8" style={glass}>
                    <div className="mb-4 flex items-center gap-4">
                      <div className="w-12 h-12 rounded-xl flex flex-shrink-0 items-center justify-center" style={{ background: 'rgba(34,197,94,0.12)' }}>
                        <Icon className="w-6 h-6 text-[#16a34a]" />
                      </div>
                      <h3 className="text-lg font-bold text-primary-main" style={{ fontFamily: '"Poppins", sans-serif' }}>{title}</h3>
                    </div>
                    <p className="text-sm text-[#516A80] leading-relaxed" style={{ fontFamily: '"Inter", sans-serif' }}>{body}</p>
                  </div>
                ))}
              </div>
            </div>
            <div>
              {renderSectionHeading(<>Built for landlords <span className="text-[#16a34a]">short on time</span></>)}
              {renderDetailGrid([
                { title: 'Portfolio-wide coverage', body: 'One summary spans every property and unit you manage — not just the one you happen to be looking at.' },
                { title: 'Plain English, always', body: "No dashboards to interpret, no numbers to cross-reference. Just a clear paragraph that tells you what's going on." },
                { title: 'Always current', body: 'Summaries reflect your latest data every time you open them — no manual refresh needed.' },
                { title: 'Available from your dashboard', body: 'Accessible right where you already work. No extra app, no separate tab.' },
                { title: 'Saves meaningful time', body: 'What used to take 20 minutes of report-hopping now takes seconds. Do it daily without the overhead.' },
                { title: 'Included in Premium', body: 'No add-on fee. Percy AI Summaries is part of your Property Peace Premium subscription.' },
              ])}
            </div>
            {renderCTA('Your portfolio at a glance — always.', 'Percy AI Summaries is included with Premium. No extra cost, no setup — just instant clarity every time you log in.', <FiActivity className="w-7 h-7 text-white" />, 'Get Started Free')}
          </div>
        </div>
      </>
    );
  }

  // ── Rent Estimate ─────────────────────────────────────────────────────────
  if (slug === 'rent-estimate') {
    return (
      <>
        {structuredData()}
        <div className="relative overflow-hidden bg-white">
          <div className="absolute inset-0 pointer-events-none opacity-[0.04]" style={{ backgroundImage: 'radial-gradient(circle, #16a34a 1px, transparent 1px)', backgroundSize: '28px 28px' }} />
          <div className="relative">
            {renderHero(
              'Data-Driven Rent Estimates for Independent Landlords',
              'Know exactly what your unit is worth before you list. Real comparable listings, data-driven ranges, and the confidence to price right every time.',
              'Premium Feature',
              'Try Rent Estimates Free',
              ['Real comparable listings', 'Address-level accuracy', 'Instant results', 'Included with Premium']
            )}
          </div>
        </div>
        <div className="bg-white">
          <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-16">
            {renderBeforeAfter('Rent Estimates',
              ['Guessing based on old listings and gut feel', 'Underpricing — losing hundreds of dollars every month', 'Overpricing — sitting vacant while the market moves on', 'Hours manually searching Zillow and Craigslist', 'Second-guessing every price change'],
              ['Instant rent range based on real nearby listings', 'Price confidently — maximize income from day one', 'Attract quality tenants faster at the right price', 'No more manual market research before listing', 'Make data-backed decisions on every unit'],
              <FiTrendingUp className="w-5 h-5 text-[#16a34a]" />
            )}
            <div>
              {renderSectionHeading(<>How it <span className="text-[#16a34a]">works</span></>)}
              {renderStepCards([
                { icon: FiMapPin, step: '01', title: 'Select your unit', body: 'Open any unit in your Property Peace dashboard. Rent Estimates is available right inline — no separate tool or tab needed.' },
                { icon: FiGlobe, step: '02', title: 'We scan the market', body: "We pull real comparable rental listings near your property's address — filtered by unit type, bedroom count, and proximity." },
                { icon: FiTrendingUp, step: '03', title: 'You get a rent range', body: 'See a clear low–high rent range backed by actual listings, so you can price with confidence before you list.' },
              ])}
            </div>
            <div>
              {renderSectionHeading(<>Price right. <span className="text-[#16a34a]">Every time.</span></>)}
              {renderDetailGrid([
                { title: 'Real comparables', body: 'Estimates are based on actual rental listings near your address — not broad regional averages or generic algorithms.' },
                { title: 'Address-level accuracy', body: "Results are scoped to your property's location so you see what similar units are actually renting for nearby." },
                { title: 'Instant results', body: 'No waiting, no manual research. Open a unit, run an estimate, and get a range in seconds.' },
                { title: 'Filtered by unit type', body: "Comparables are matched to your unit's bedroom count and type so you're comparing apples to apples." },
                { title: 'Available per unit', body: 'Run estimates for any unit in your portfolio — right from the unit detail page inside your dashboard.' },
                { title: 'Included in Premium', body: 'No add-on fee. Rent Estimates is part of your Property Peace Premium subscription.' },
              ])}
            </div>
            {renderCTA('Stop leaving money on the table.', 'Rent Estimates is included with Premium. Get data-driven pricing for every unit before you list — no extra cost.', <FiTrendingUp className="w-7 h-7 text-white" />, 'Get Started Free')}
          </div>
        </div>
      </>
    );
  }

  // ── LeaseShield ───────────────────────────────────────────────────────────
  if (slug === 'lease-shield') {
    return (
      <>
        {structuredData()}
        <div className="relative overflow-hidden bg-white">
          <div className="absolute inset-0 pointer-events-none opacity-[0.04]" style={{ backgroundImage: 'radial-gradient(circle, #16a34a 1px, transparent 1px)', backgroundSize: '28px 28px' }} />
          <div className="relative">
            {renderHero(
              <>Lease<span className="text-green-600">Shield</span></>,
              'Lease and landlord–tenant law answers sourced exclusively from government statutes, attorney general guides, and official .gov sites — never generic AI or random blogs.',
              'Premium Feature',
              'Try LeaseShield Free',
              ['Official .gov sources only', 'State-specific answers', 'Citable statute links', 'Included with Premium']
            )}
          </div>
        </div>
        <div className="bg-white">
          <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-16">
            {renderBeforeAfter('LeaseShield',
              ['Generic AI that cites blogs and opinion sites', "No idea if the answer applies to your state", 'No citations — nothing to show a tenant or attorney', 'Risk of acting on outdated or incorrect information', 'Hours spent searching .gov sites yourself'],
              ['Every answer drawn from government statutes & .gov sites', 'State selection so guidance matches your jurisdiction', 'Direct citations and links you can share or reference', 'Accurate, defensible info you can stand behind', 'Answers in seconds — right inside Property Peace'],
              <FiShield className="w-5 h-5 text-[#16a34a]" />
            )}
            <div>
              {renderSectionHeading(<>How it <span className="text-[#16a34a]">works</span></>)}
              {renderStepCards([
                { icon: FiGlobe, step: '01', title: 'Select your state', body: "Tell LeaseShield which state your property is in. Every answer is filtered to match that jurisdiction's statutes and housing agency guidance." },
                { icon: FiMessageSquare, step: '02', title: 'Ask your question', body: 'Type any lease or landlord–tenant law question in plain English. LeaseShield searches only official government and state law sources — never third-party blogs.' },
                { icon: FiBookOpen, step: '03', title: 'Get a cited answer', body: 'Receive a clear, plain-English answer with direct links to the statutes, attorney general guides, or .gov housing pages that back it up.' },
              ])}
            </div>
            <div>
              {renderSectionHeading(<>Everything you need to <span className="text-[#16a34a]">stay compliant</span></>)}
              {renderDetailGrid([
                { title: 'Government sources only', body: 'Answers come exclusively from statutes, .gov sites, and state attorney general or housing agency publications — nothing else.' },
                { title: 'State-specific context', body: "Select your state once per lease. Every follow-up answer stays grounded in that jurisdiction's law, not a national generalization." },
                { title: 'Cited statute links', body: 'Every answer includes direct links to the exact source so you can verify, share, or reference it if challenged by a tenant or attorney.' },
                { title: 'Lease-linked history', body: 'Conversations are tied to a specific lease so context carries over. Ask a follow-up days later and LeaseShield still knows the full picture.' },
                { title: 'Plain-English answers', body: "Legal language made readable. LeaseShield explains what the law actually means for your situation without the legalese." },
                { title: 'Included in Premium', body: 'No add-on fee. LeaseShield is part of your Property Peace Premium subscription — use it as often as you need.' },
              ])}
            </div>
            {renderCTA("Stop guessing. Start knowing.", "LeaseShield gives you Percy-powered, legally grounded answers that generic AI tools simply can't provide. Included with Premium — no extra cost.", <FiShield className="w-7 h-7 text-white" />, 'Get Started Free')}
          </div>
        </div>
      </>
    );
  }

  // ── Generic feature page ──────────────────────────────────────────────────
  const titleWords = (ottoFeatureH1Overrides[slug] ?? feature.title).split(' ');
  const accentWord = titleWords.slice(-1)[0];
  const restWords  = titleWords.slice(0, -1).join(' ');
  const ottoFeatureH2 = ottoFeatureH2Overrides[slug];
  const isRentCollectionFeature = slug === 'rent-collection';
  const isMaintenanceTrackingFeature = slug === 'maintenance-tracking';

  const rentCollectionHeroTitle = ottoFeatureH1Overrides[slug] ?? 'Online Rent Collection for Independent Landlords';

  const renderRentCollectionHero = () => (
    <div className="relative overflow-hidden bg-white">
      <div className="absolute inset-0 pointer-events-none opacity-[0.04]" style={{ backgroundImage: 'radial-gradient(circle, #0a2d52 1px, transparent 1px)', backgroundSize: '28px 28px' }} />
      <div className="relative mx-auto max-w-6xl px-4 pb-14 pt-24 sm:px-6 sm:pb-18 sm:pt-10 lg:px-8 lg:pb-20">
        <Link href="/features" className="mb-10 inline-flex items-center text-[#516A80] transition-colors hover:text-green-600" style={{ fontFamily: '"Inter", sans-serif' }}>
          <FiArrowLeft className="mr-2 h-4 w-4" />Back to Features
        </Link>

        <div className="grid items-center gap-10 lg:grid-cols-[minmax(0,0.95fr)_minmax(420px,1.05fr)] lg:gap-12">
          <div className="text-center lg:text-left">
            <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#E5E5E5] bg-white px-3.5 py-2 text-xs font-semibold uppercase leading-snug tracking-widest text-green-600 shadow-sm" style={{ fontFamily: '"Inter", sans-serif' }}>
              Rent Collection
            </div>

            <h1 className="mb-5 text-[2.3rem] font-bold leading-[1.08] text-primary-main sm:text-5xl md:text-6xl" style={{ fontFamily: '"Poppins", sans-serif' }}>
              {rentCollectionHeroTitle}
            </h1>
            <p className="mx-auto mb-7 max-w-2xl text-[17px] leading-relaxed text-[#737373] md:text-xl lg:mx-0" style={{ fontFamily: '"Inter", sans-serif' }}>
              {feature.shortDescription}
            </p>

            <div className="mx-auto grid max-w-[22rem] grid-cols-2 justify-center gap-2.5 sm:flex sm:max-w-none sm:flex-row sm:justify-center sm:gap-3 lg:mx-0 lg:justify-start">
              <Link href="https://app.propertypeace.io/register" className="inline-flex min-h-[50px] items-center justify-center gap-2 rounded-none bg-gradient-to-r from-green-500 to-green-600 px-4 py-3 text-sm font-semibold text-white shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:from-green-600 hover:to-green-700 sm:min-h-[56px] rounded-none sm:px-8 sm:text-base" style={{ fontFamily: '"Inter", sans-serif' }}>
                <FiZap className="h-4 w-4" />Start free
              </Link>
              <Link href="/pricing" className="inline-flex min-h-[50px] items-center justify-center gap-2 rounded-none border border-[#E5E5E5] bg-white px-4 py-3 text-sm font-semibold text-primary-main shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:border-green-300 hover:text-green-600 sm:min-h-[56px] rounded-none sm:px-8 sm:text-base" style={{ fontFamily: '"Inter", sans-serif' }}>
                View Pricing
              </Link>
            </div>

            <div className="mt-5 grid grid-cols-2 gap-2 text-[13px] font-semibold text-primary-main sm:flex sm:flex-wrap lg:justify-start" style={{ fontFamily: '"Inter", sans-serif' }}>
              {['Track paid & overdue rent', 'Send reminders fast', 'Update the ledger automatically', 'Free for up to 2 units'].map((item) => (
                <span key={item} className="inline-flex min-h-[40px] items-center justify-center gap-2 rounded-2xl border border-[#E5E5E5] bg-white px-3 py-2 leading-snug shadow-sm sm:min-h-0 sm:rounded-full sm:py-1">
                  <FiCheck className="h-4 w-4 flex-shrink-0 text-green-600" />{item}
                </span>
              ))}
            </div>
          </div>

          <RentCollectionHeroMock />
        </div>
      </div>
    </div>
  );

  return (
    <>
      {structuredData()}
      {isRentCollectionFeature ? renderRentCollectionHero() : isMaintenanceTrackingFeature ? renderMaintenanceTrackingHero() : (
        <div className="relative overflow-hidden bg-white">
          <div className="absolute inset-0 pointer-events-none opacity-[0.04]" style={{ backgroundImage: 'radial-gradient(circle, #16a34a 1px, transparent 1px)', backgroundSize: '28px 28px' }} />
          <div className="relative">
            {renderHero(
              restWords ? <>{restWords} <span className="text-green-600">{accentWord}</span></> : <span className="text-green-600">{accentWord}</span>,
              feature.shortDescription,
              undefined,
              'Get Started Free',
              feature.benefits.slice(0, 4)
            )}
          </div>
        </div>
      )}
      <div className="bg-white">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-16">
          {isMaintenanceTrackingFeature ? (
            <MaintenanceTrackingFeatureSection
              heading={ottoFeatureH2 ?? 'Streamline Maintenance and Work Order Tracking'}
              description={feature.description}
              benefits={feature.benefits}
            />
          ) : (
            <div className="mx-auto max-w-3xl text-center">
              <p className="text-lg md:text-xl text-[#516A80] leading-relaxed" style={{ fontFamily: '"Inter", sans-serif' }}>
                {feature.description}
              </p>
            </div>
          )}
          {!isMaintenanceTrackingFeature && (
            <div>
              {renderSectionHeading(
                slug === 'lease-management'
                  ? <>Lease Management <span className="text-[#16a34a]">Features</span></>
                  : ottoFeatureH2 ?? <>What you <span className="text-[#16a34a]">get</span></>
              )}
              <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
                {feature.benefits.map((benefit, i) => (
                  <div key={i} className="rounded-2xl p-6 transition-all duration-200 hover:bg-green-50/70" style={glass}>
                    <div className="w-8 h-8 rounded-lg flex items-center justify-center mb-4" style={{ background: 'rgba(34,197,94,0.12)' }}>
                      <FiCheck className="w-4 h-4 text-[#16a34a]" />
                    </div>
                    <p className="text-sm text-[#2d4a62] font-medium leading-relaxed" style={{ fontFamily: '"Inter", sans-serif' }}>{benefit}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
          {isMaintenanceTrackingFeature ? (
            <div>
              <h2 className="mb-8 text-left text-2xl font-bold text-primary-main md:text-3xl" style={{ fontFamily: '"Poppins", sans-serif' }}>
                Everything <span className="text-[#16a34a]">included</span>
              </h2>
              <div className="rounded-2xl p-8 md:p-12" style={glassDim}>
                <div className="grid sm:grid-cols-2 gap-4">
                  {feature.features.map((item, i) => (
                    <div key={i} className="flex items-start gap-3">
                      <div className="w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5" style={{ background: 'rgba(34,197,94,0.12)' }}>
                        <FiCheck className="w-3.5 h-3.5 text-[#16a34a]" />
                      </div>
                      <p className="text-sm text-[#516A80] leading-relaxed" style={{ fontFamily: '"Inter", sans-serif' }}>{item}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ) : (
            <div className="rounded-2xl p-8 md:p-12" style={glassDim}>
              <h2 className="text-2xl md:text-3xl font-bold text-primary-main mb-8" style={{ fontFamily: '"Poppins", sans-serif' }}>
                Everything <span className="text-[#16a34a]">included</span>
              </h2>
              <div className="grid sm:grid-cols-2 gap-4">
                {feature.features.map((item, i) => (
                  <div key={i} className="flex items-start gap-3">
                    <div className="w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5" style={{ background: 'rgba(34,197,94,0.12)' }}>
                      <FiCheck className="w-3.5 h-3.5 text-[#16a34a]" />
                    </div>
                    <p className="text-sm text-[#516A80] leading-relaxed" style={{ fontFamily: '"Inter", sans-serif' }}>{item}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
          {renderCTA(`Ready to try ${feature.title}?`, 'Start free with Property Peace. No credit card required, and built for 1–50 unit landlords.', <IconComponent className="w-7 h-7 text-white" />, 'Start free')}
        </div>
      </div>
    </>
  );
}
