import { useMemo, useState } from 'react';
import { Link as RouterLink, useNavigate } from 'react-router-dom';
import {
  alpha,
  Avatar,
  Box,
  Button,
  Chip,
  CircularProgress,
  Grid,
  InputAdornment,
  OutlinedInput,
  Stack,
  Typography,
  useTheme
} from '@mui/material';
import {
  ArrowRightOutlined,
  BarChartOutlined,
  CalculatorOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  DollarCircleOutlined,
  FileDoneOutlined,
  FileTextOutlined,
  HomeOutlined,
  LockOutlined,
  ReloadOutlined,
  RocketOutlined,
  SearchOutlined,
  SettingOutlined,
  TrophyOutlined,
  UserOutlined
} from '@ant-design/icons';
import AnimateIn from 'components/AnimateIn';
import PageBreadcrumbs from 'components/breadcrumbs/PageBreadcrumbs';
import useEntitlement from 'hooks/useEntitlement';
import { ADVANCED_REPORTING_FEATURE } from 'utils/entitlements';

const NAVY = '#061e35';
const GREEN = '#22c55e';

const REPORTS = [
  {
    id: 'tax-reports',
    title: 'Tax & Accounting',
    description: 'Review deductible expenses, tax readiness, Schedule E data, and 1099 preparation in one workspace.',
    icon: <FileTextOutlined />,
    color: '#7c3aed',
    route: '/landlord/reports/tax',
    group: 'Money & tax',
    eyebrow: 'Year-end ready',
    featured: true
  },
  {
    id: 'financial-reports',
    title: 'Financial Performance',
    description: 'Understand income, expenses, profitability, trends, and year-over-year portfolio performance.',
    icon: <CalculatorOutlined />,
    color: '#2563eb',
    route: '/landlord/reports/financial',
    group: 'Money & tax',
    eyebrow: 'Exportable',
    featured: true
  },
  {
    id: 'occupancy',
    title: 'Occupancy',
    description: 'Track occupied and vacant units over time and identify portfolio availability trends.',
    icon: <HomeOutlined />,
    color: '#16a34a',
    route: '/landlord/reports/occupancy',
    group: 'Portfolio',
    eyebrow: 'Core portfolio KPI',
    featured: true
  },
  {
    id: 'revenue-per-unit',
    title: 'Revenue Per Unit',
    description: 'Compare the revenue generated by each unit under management.',
    icon: <DollarCircleOutlined />,
    color: '#0891b2',
    route: '/landlord/reports/revenue-per-unit',
    group: 'Portfolio',
    eyebrow: 'Revenue efficiency'
  },
  {
    id: 'median-ttt',
    title: 'Median Turn Time',
    description: 'Measure how long it takes to prepare a unit for the next resident after move-out.',
    icon: <ClockCircleOutlined />,
    color: '#d97706',
    route: '/landlord/reports/median-ttt',
    group: 'Operations',
    eyebrow: 'Make-ready speed'
  },
  {
    id: 'median-dom',
    title: 'Median Days on Market',
    description: 'Measure the time between listing a unit and securing a signed lease.',
    icon: <BarChartOutlined />,
    color: '#db2777',
    route: '/landlord/reports/median-dom',
    group: 'Operations',
    eyebrow: 'Leasing velocity'
  },
  {
    id: 'units-per-employee',
    title: 'Units Per Employee',
    description: 'Understand team capacity by comparing managed units with direct team members.',
    icon: <UserOutlined />,
    color: '#ea580c',
    route: '/landlord/reports/units-per-employee',
    group: 'Operations',
    eyebrow: 'Team efficiency'
  },
  {
    id: 'units-per-client',
    title: 'Units Per Client',
    description: 'Compare portfolio concentration and managed unit counts across property-owner relationships.',
    icon: <HomeOutlined />,
    color: '#0f766e',
    route: '/landlord/reports/units-per-client',
    group: 'Operations',
    eyebrow: 'Client concentration'
  },
  {
    id: 'client-churn',
    title: 'Client Churn',
    description: 'Review client retention patterns and identify changes in managed relationships over time.',
    icon: <UserOutlined />,
    color: '#be123c',
    route: '/landlord/reports/client-churn',
    group: 'Operations',
    eyebrow: 'Retention trend'
  },
  {
    id: 'closing-rate',
    title: 'Closing Rate',
    description: 'Understand how consistently qualified leasing opportunities become signed leases.',
    icon: <CheckCircleOutlined />,
    color: '#15803d',
    route: '/landlord/reports/closing-rate',
    group: 'Operations',
    eyebrow: 'Leasing conversion'
  },
  {
    id: 'nps-client',
    title: 'Client NPS Score',
    description: 'Monitor property-owner satisfaction and likelihood to recommend your management services.',
    icon: <TrophyOutlined />,
    color: '#6d28d9',
    route: '/landlord/reports/nps-client',
    group: 'Experience',
    eyebrow: 'Client sentiment'
  },
  {
    id: 'nps-tenant',
    title: 'Tenant NPS Score',
    description: 'Monitor resident satisfaction and their likelihood to recommend their rental experience.',
    icon: <TrophyOutlined />,
    color: '#4f46e5',
    route: '/landlord/reports/nps-tenant',
    group: 'Experience',
    eyebrow: 'Resident sentiment'
  }
];

const FILTERS = ['All reports', 'Money & tax', 'Portfolio', 'Operations', 'Experience'];

const ACCESS_LABELS = {
  allowed: 'Reporting access active',
  upgrade: 'Premium workspace',
  setup: 'Setup required',
  unauthorized: 'Access restricted',
  unavailable: 'Access unavailable'
};

function Hero({ locked, showUpgrade, presentationKind }) {
  const navigate = useNavigate();

  return (
    <Box
      sx={{
        position: 'relative',
        overflow: 'hidden',
        borderRadius: 3,
        bgcolor: NAVY,
        color: '#fff',
        px: { xs: 2.5, md: 4 },
        py: { xs: 3, md: 4 },
        boxShadow: `0 18px 45px ${alpha(NAVY, 0.18)}`,
        '&::after': {
          content: '""',
          position: 'absolute',
          width: 320,
          height: 320,
          right: -100,
          top: -180,
          borderRadius: '50%',
          bgcolor: alpha(GREEN, 0.14)
        }
      }}
    >
      <Stack
        direction={{ xs: 'column', md: 'row' }}
        justifyContent="space-between"
        alignItems={{ xs: 'flex-start', md: 'center' }}
        spacing={3}
      >
        <Box sx={{ position: 'relative', zIndex: 1, maxWidth: 700 }}>
          <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap sx={{ mb: 1.5 }}>
            <Chip
              size="small"
              icon={locked ? <LockOutlined /> : <CheckCircleOutlined />}
              label={ACCESS_LABELS[presentationKind] || ACCESS_LABELS.unavailable}
              sx={{ bgcolor: alpha('#fff', 0.12), color: '#fff', '& .MuiChip-icon': { color: locked ? '#fbbf24' : GREEN } }}
            />
            <Chip size="small" label={`${REPORTS.length} live reports`} sx={{ bgcolor: alpha('#fff', 0.08), color: alpha('#fff', 0.82) }} />
          </Stack>
          <Typography variant="h2" sx={{ color: '#fff', fontWeight: 780, letterSpacing: -0.7 }}>
            Turn portfolio data into better decisions.
          </Typography>
          <Typography sx={{ mt: 1.25, color: alpha('#fff', 0.72), maxWidth: 620, lineHeight: 1.7 }}>
            Review financial performance, tax readiness, occupancy, leasing velocity, and operating efficiency from one focused workspace.
          </Typography>
        </Box>

        <Stack
          direction={{ xs: 'column', sm: 'row', md: 'column' }}
          spacing={1.25}
          sx={{ width: { xs: '100%', sm: 'auto' }, position: 'relative', zIndex: 1 }}
        >
          {locked && showUpgrade ? (
            <Button
              variant="contained"
              startIcon={<RocketOutlined />}
              onClick={() => navigate('/landlord/settings?tab=subscription')}
              sx={{ minHeight: 44, bgcolor: GREEN, color: NAVY, fontWeight: 750, '&:hover': { bgcolor: '#16a34a', color: '#fff' } }}
            >
              View subscription
            </Button>
          ) : !locked ? (
            <>
              <Button
                variant="contained"
                startIcon={<FileDoneOutlined />}
                onClick={() => navigate('/landlord/reports/tax')}
                sx={{ minHeight: 44, bgcolor: GREEN, color: NAVY, fontWeight: 750, '&:hover': { bgcolor: '#16a34a', color: '#fff' } }}
              >
                Open tax workspace
              </Button>
              <Button
                variant="outlined"
                endIcon={<ArrowRightOutlined />}
                onClick={() => navigate('/landlord/reports/financial')}
                sx={{
                  minHeight: 44,
                  color: '#fff',
                  borderColor: alpha('#fff', 0.32),
                  '&:hover': { borderColor: '#fff', bgcolor: alpha('#fff', 0.06) }
                }}
              >
                View financials
              </Button>
            </>
          ) : null}
        </Stack>
      </Stack>
    </Box>
  );
}

function FeaturedReport({ report, locked }) {
  const navigate = useNavigate();
  const theme = useTheme();

  return (
    <Box
      component="button"
      type="button"
      onClick={() => !locked && navigate(report.route)}
      disabled={locked}
      aria-disabled={locked}
      sx={{
        width: '100%',
        height: '100%',
        minHeight: 174,
        p: 2.25,
        borderRadius: 2.5,
        border: `1px solid ${alpha(report.color, 0.2)}`,
        bgcolor: 'background.paper',
        color: 'text.primary',
        textAlign: 'left',
        font: 'inherit',
        cursor: locked ? 'default' : 'pointer',
        boxShadow: `0 6px 24px ${alpha(NAVY, 0.055)}`,
        transition: 'transform 160ms ease, box-shadow 160ms ease, border-color 160ms ease',
        '&:hover': locked
          ? {}
          : {
              transform: 'translateY(-3px)',
              borderColor: alpha(report.color, 0.45),
              boxShadow: `0 14px 32px ${alpha(report.color, 0.12)}`
            },
        '&:focus-visible': { outline: `3px solid ${alpha(report.color, 0.25)}`, outlineOffset: 2 }
      }}
    >
      <Stack height="100%" justifyContent="space-between" spacing={2}>
        <Stack direction="row" justifyContent="space-between" alignItems="flex-start">
          <Avatar
            variant="rounded"
            sx={{ width: 44, height: 44, borderRadius: 2, bgcolor: alpha(report.color, 0.11), color: report.color, fontSize: 20 }}
          >
            {report.icon}
          </Avatar>
          {locked ? (
            <LockOutlined style={{ color: theme.palette.text.disabled }} />
          ) : (
            <ArrowRightOutlined style={{ color: report.color }} />
          )}
        </Stack>
        <Box>
          <Typography sx={{ fontSize: '0.7rem', color: report.color, fontWeight: 750, letterSpacing: 0.65, textTransform: 'uppercase' }}>
            {report.eyebrow}
          </Typography>
          <Typography sx={{ mt: 0.55, fontSize: '1rem', fontWeight: 750 }}>{report.title}</Typography>
          <Typography sx={{ mt: 0.65, color: 'text.secondary', fontSize: '0.78rem', lineHeight: 1.55 }}>{report.description}</Typography>
        </Box>
      </Stack>
    </Box>
  );
}

function ReportCard({ report, locked }) {
  const navigate = useNavigate();
  const theme = useTheme();

  return (
    <Box
      component="button"
      type="button"
      onClick={() => !locked && navigate(report.route)}
      disabled={locked}
      aria-disabled={locked}
      sx={{
        width: '100%',
        p: { xs: 1.75, md: 2 },
        height: '100%',
        borderRadius: 2.25,
        border: `1px solid ${alpha(theme.palette.divider, 0.16)}`,
        bgcolor: 'background.paper',
        color: 'text.primary',
        textAlign: 'left',
        font: 'inherit',
        cursor: locked ? 'default' : 'pointer',
        boxShadow: `0 3px 16px ${alpha(NAVY, 0.04)}`,
        transition: 'border-color 150ms ease, transform 150ms ease, box-shadow 150ms ease',
        '&:hover': locked
          ? {}
          : {
              transform: 'translateY(-2px)',
              borderColor: alpha(report.color, 0.38),
              boxShadow: `0 10px 26px ${alpha(report.color, 0.09)}`
            },
        '&:focus-visible': { outline: `3px solid ${alpha(report.color, 0.22)}`, outlineOffset: 2 }
      }}
    >
      <Stack direction="row" spacing={1.5} alignItems="flex-start">
        <Avatar
          variant="rounded"
          sx={{ width: 42, height: 42, borderRadius: 1.7, bgcolor: alpha(report.color, 0.1), color: report.color, flexShrink: 0 }}
        >
          {report.icon}
        </Avatar>
        <Box sx={{ flex: 1, minWidth: 0 }}>
          <Stack direction="row" justifyContent="space-between" alignItems="center" spacing={1}>
            <Typography fontWeight={750}>{report.title}</Typography>
            {locked ? (
              <LockOutlined style={{ color: theme.palette.text.disabled }} />
            ) : (
              <ArrowRightOutlined style={{ color: theme.palette.text.secondary, fontSize: 13 }} />
            )}
          </Stack>
          <Typography sx={{ mt: 0.45, color: 'text.secondary', fontSize: '0.76rem', lineHeight: 1.5 }}>{report.description}</Typography>
          <Stack direction="row" spacing={0.75} alignItems="center" sx={{ mt: 1.2 }}>
            <Chip
              size="small"
              label={report.group}
              sx={{ height: 22, fontSize: '0.66rem', bgcolor: alpha(report.color, 0.08), color: report.color, fontWeight: 650 }}
            />
            <Typography sx={{ color: 'text.secondary', fontSize: '0.68rem' }}>{report.eyebrow}</Typography>
          </Stack>
        </Box>
      </Stack>
    </Box>
  );
}

function ReportLibrary({ locked }) {
  const theme = useTheme();
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('All reports');

  const filteredReports = useMemo(() => {
    const normalized = query.trim().toLowerCase();
    return REPORTS.filter((report) => {
      const matchesFilter = filter === 'All reports' || report.group === filter;
      const searchable = `${report.title} ${report.description} ${report.group} ${report.eyebrow}`.toLowerCase();
      return matchesFilter && (!normalized || searchable.includes(normalized));
    });
  }, [filter, query]);

  return (
    <Stack spacing={2.5}>
      <Box>
        <Typography variant="h4" fontWeight={750}>
          Recommended starting points
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
          The reports landlords use most often for monthly reviews and year-end preparation.
        </Typography>
      </Box>

      <Grid container spacing={2}>
        {REPORTS.filter((report) => report.featured).map((report) => (
          <Grid key={report.id} size={{ xs: 12, md: 4 }}>
            <FeaturedReport report={report} locked={locked} />
          </Grid>
        ))}
      </Grid>

      <Box sx={{ pt: 1 }}>
        <Stack
          direction={{ xs: 'column', md: 'row' }}
          justifyContent="space-between"
          alignItems={{ xs: 'stretch', md: 'flex-end' }}
          spacing={2}
        >
          <Box>
            <Typography variant="h4" fontWeight={750}>
              Report library
            </Typography>
            <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
              Find the exact view you need by topic or keyword.
            </Typography>
          </Box>
          <OutlinedInput
            size="small"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Search reports"
            startAdornment={
              <InputAdornment position="start">
                <SearchOutlined />
              </InputAdornment>
            }
            sx={{ width: { xs: '100%', md: 270 }, minHeight: 44, bgcolor: 'background.paper' }}
          />
        </Stack>

        <Stack direction="row" spacing={1} sx={{ mt: 2, overflowX: 'auto', pb: 0.5 }}>
          {FILTERS.map((item) => {
            const active = filter === item;
            return (
              <Chip
                key={item}
                label={item}
                clickable
                onClick={() => setFilter(item)}
                sx={{
                  minHeight: 44,
                  flexShrink: 0,
                  fontWeight: 650,
                  bgcolor: active ? NAVY : 'background.paper',
                  color: active ? '#fff' : 'text.secondary',
                  border: `1px solid ${active ? NAVY : alpha(theme.palette.divider, 0.2)}`,
                  '&:hover': { bgcolor: active ? NAVY : alpha(NAVY, 0.05) }
                }}
              />
            );
          })}
        </Stack>
      </Box>

      {filteredReports.length ? (
        <Grid container spacing={1.75}>
          {filteredReports.map((report) => (
            <Grid key={report.id} size={{ xs: 12, lg: 6 }}>
              <ReportCard report={report} locked={locked} />
            </Grid>
          ))}
        </Grid>
      ) : (
        <Box sx={{ py: 7, px: 2, textAlign: 'center', borderRadius: 2.5, border: `1px dashed ${alpha(theme.palette.divider, 0.35)}` }}>
          <SearchOutlined style={{ fontSize: 28, color: theme.palette.text.disabled }} />
          <Typography fontWeight={700} sx={{ mt: 1.5 }}>
            No reports match your search
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
            Try another keyword or choose a different topic.
          </Typography>
          <Button
            size="small"
            onClick={() => {
              setQuery('');
              setFilter('All reports');
            }}
            sx={{ mt: 1.5, minHeight: 44 }}
          >
            Clear filters
          </Button>
        </Box>
      )}
    </Stack>
  );
}

function AccessNotice({ kind, refresh }) {
  const setup = kind === 'setup';
  const unauthorized = kind === 'unauthorized';
  const unavailable = kind === 'unavailable';
  const upgrade = kind === 'upgrade';

  const content = setup
    ? {
        title: 'Finish setting up your organization',
        message: 'Reporting needs an active organization before portfolio data can be loaded securely.'
      }
    : unauthorized
      ? {
          title: 'You do not have access to reporting',
          message: 'Ask an organization owner or administrator to review your reporting access. No billing changes are needed.'
        }
      : unavailable
        ? {
            title: 'Reporting access cannot be confirmed',
            message: 'Reports remain safely unavailable while access is checked. Try again, and contact support if the problem continues.'
          }
        : {
            title: 'Preview the complete analytics workspace',
            message: 'Premium unlocks every report below, including financial exports, tax preparation views, and portfolio trends.'
          };

  return (
    <Box
      aria-live="polite"
      sx={{ px: { xs: 2, md: 2.5 }, py: 1.75, borderRadius: 2.25, border: `1px solid ${alpha(GREEN, 0.24)}`, bgcolor: alpha(GREEN, 0.055) }}
    >
      <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.25} alignItems={{ xs: 'stretch', sm: 'center' }}>
        <Box sx={{ flex: 1 }}>
          <Typography variant="body2" fontWeight={750}>
            {content.title}
          </Typography>
          <Typography variant="caption" color="text.secondary">
            {content.message}
          </Typography>
        </Box>
        {setup && (
          <Button
            component={RouterLink}
            to="/landlord/admin-members"
            variant="contained"
            startIcon={<SettingOutlined />}
            sx={{ minHeight: 44 }}
          >
            Choose organization
          </Button>
        )}
        {unavailable && (
          <Button type="button" variant="outlined" startIcon={<ReloadOutlined />} onClick={refresh} sx={{ minHeight: 44 }}>
            Try again
          </Button>
        )}
        {upgrade && (
          <Button
            component={RouterLink}
            to="/landlord/settings?tab=subscription"
            variant="contained"
            startIcon={<RocketOutlined />}
            sx={{ minHeight: 44 }}
          >
            View subscription
          </Button>
        )}
      </Stack>
    </Box>
  );
}

export default function ReportsDashboard() {
  const { presentation, canInvoke, refresh } = useEntitlement(ADVANCED_REPORTING_FEATURE);
  const locked = !canInvoke;
  const showUpgrade = presentation.kind === 'upgrade';
  const showSetup = presentation.kind === 'setup';
  const showUnauthorized = presentation.kind === 'unauthorized';
  const showUnavailable = presentation.kind === 'unavailable';
  const showAccessNotice = showUpgrade || showSetup || showUnauthorized || showUnavailable;

  if (presentation.kind === 'loading') {
    return (
      <Box>
        <PageBreadcrumbs items={[{ label: 'Dashboard', path: '/landlord/dashboard' }, { label: 'Reports & Analytics' }]} />
        <Box
          aria-live="polite"
          aria-busy="true"
          sx={{ display: 'flex', flexDirection: 'column', gap: 1.5, justifyContent: 'center', alignItems: 'center', minHeight: 400 }}
        >
          <CircularProgress aria-label="Checking reporting access" />
          <Typography color="text.secondary">Checking your reporting access…</Typography>
        </Box>
      </Box>
    );
  }

  return (
    <Box>
      <AnimateIn direction="bottom" delay={100} distance={80}>
        <PageBreadcrumbs items={[{ label: 'Dashboard', path: '/landlord/dashboard' }, { label: 'Reports & Analytics' }]} />
      </AnimateIn>

      <Stack spacing={3}>
        <AnimateIn direction="bottom" delay={180} distance={80}>
          <Hero locked={locked} showUpgrade={showUpgrade} presentationKind={presentation.kind} />
        </AnimateIn>

        {showAccessNotice && (
          <AnimateIn direction="bottom" delay={240} distance={80}>
            <AccessNotice kind={presentation.kind} refresh={refresh} />
          </AnimateIn>
        )}

        <AnimateIn direction="bottom" delay={300} distance={80}>
          <ReportLibrary locked={locked} />
        </AnimateIn>
      </Stack>
    </Box>
  );
}
