export const RENT_COLLECTION_ACTION_TYPES = {
  GET_RENT_COLLECTION_START: 'rentCollection/GET_RENT_COLLECTION_START',
  GET_RENT_COLLECTION_SUMMARY_SUCCESS: 'rentCollection/GET_RENT_COLLECTION_SUMMARY_SUCCESS',
  GET_RENT_COLLECTION_SUMMARY_FAILURE: 'rentCollection/GET_RENT_COLLECTION_SUMMARY_FAILURE',
  GET_RENT_COLLECTION_SUCCESS: 'rentCollection/GET_RENT_COLLECTION_SUCCESS',
  GET_RENT_COLLECTION_FAILURE: 'rentCollection/GET_RENT_COLLECTION_FAILURE',
  MAKE_PAYMENT_START: 'rentCollection/MAKE_PAYMENT_START',
  MAKE_PAYMENT_SUCCESS: 'rentCollection/MAKE_PAYMENT_SUCCESS',
  MAKE_PAYMENT_FAILURE: 'rentCollection/MAKE_PAYMENT_FAILURE',
  SEND_REMINDER_START: 'rentCollection/SEND_REMINDER_START',
  SEND_REMINDER_SUCCESS: 'rentCollection/SEND_REMINDER_SUCCESS',
  SEND_REMINDER_FAILURE: 'rentCollection/SEND_REMINDER_FAILURE'
};
