export const TASK_ACTION_TYPES = {
  FETCH_TASKS_START:   'task/FETCH_TASKS_START',
  FETCH_TASKS_SUCCESS: 'task/FETCH_TASKS_SUCCESS',
  FETCH_TASKS_FAILURE: 'task/FETCH_TASKS_FAILURE',

  ADD_TASK_SUCCESS:    'task/ADD_TASK_SUCCESS',
  UPDATE_TASK_SUCCESS: 'task/UPDATE_TASK_SUCCESS',
  DELETE_TASK_SUCCESS: 'task/DELETE_TASK_SUCCESS',
};
