import React, { useCallback, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Image, InputAccessoryView, Keyboard, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as Sharing from 'expo-sharing';
import * as ImagePicker from 'expo-image-picker';
import { RouteProp, useFocusEffect, useNavigation, useRoute } from '@react-navigation/native';
import MaintenanceAPI, { LocalMedia, MaintenanceAssigneeOption, MaintenanceAssignmentDirectorySource, MaintenanceAttachment, MaintenanceRequest, newIdempotencyKey } from '../../api/maintenanceAPI';
import { MaintenanceStackParamList } from '../../navigation/types';
import { currentCycleCompletionAttachmentIds, displayStatus, normalizeMaintenanceMediaFileName, validateMaintenanceMedia } from '../../features/maintenance/maintenanceModel';

type Route = RouteProp<MaintenanceStackParamList, 'LandlordMaintenanceDetail'>;
const value = (item: any, key: string) => item?.[key] ?? item?.[key[0].toUpperCase() + key.slice(1)];
const list = (item: any, key: string): any[] => value(item, key) ?? [];
const date = (input?: string | null) => input ? new Date(input).toLocaleString() : 'Not set';
const number = (input: string) => input.trim() ? Number(input) : null;
const statusIs = (status: unknown, ...values: string[]) => values.includes(String(status).toLowerCase());
const friendlyHomeName = (item: any, key: 'propertyName' | 'unitName', nestedKey: 'property' | 'unit', fallback: string) => String(value(item, key) ?? value(value(item, nestedKey), 'name') ?? fallback);
const MONEY_KEYBOARD_ACCESSORY_ID = 'maintenance-money-keyboard';

export default function LandlordMaintenanceDetailScreen() {
  const navigation = useNavigation<any>();
  const { requestId, listItem } = useRoute<Route>().params;
  const [item, setItem] = useState<MaintenanceRequest>(listItem ?? {});
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [preview, setPreview] = useState<{ id: number; uri: string } | null>(null);
  const [assignmentOptions, setAssignmentOptions] = useState<MaintenanceAssigneeOption[]>([]); const [directoryError, setDirectoryError] = useState(''); const [directoryFailedSources, setDirectoryFailedSources] = useState<MaintenanceAssignmentDirectorySource[]>([]);
  const [assigneeType, setAssigneeType] = useState<'Self' | 'OrganizationMember' | 'Vendor'>('Self'); const [assigneeId, setAssigneeId] = useState(''); const [estimateRequired, setEstimateRequired] = useState(true);
  const [scope, setScope] = useState(''); const [amount, setAmount] = useState(''); const [estimateRejectReason, setEstimateRejectReason] = useState('');
  const [appointmentCancelReason, setAppointmentCancelReason] = useState(''); const [workOrderCancelReason, setWorkOrderCancelReason] = useState('');
  const [resolutionNotes, setResolutionNotes] = useState(''); const [staffCloseReason, setStaffCloseReason] = useState(''); const [finalCost, setFinalCost] = useState('');
  const [completionMedia, setCompletionMedia] = useState<LocalMedia[]>([]);
  const [uploadedCompletionAttachmentIds, setUploadedCompletionAttachmentIds] = useState<number[]>([]);
  const actionKeys = useRef<Record<string, string>>({});
  const keyFor = (action: string) => actionKeys.current[action] ?? (actionKeys.current[action] = newIdempotencyKey());
  const completedAction = (action: string) => { delete actionKeys.current[action]; };
  const load = useCallback(async () => { try { setError(''); const [detail, directory] = await Promise.all([MaintenanceAPI.getDetail(requestId), MaintenanceAPI.getAssignmentDirectory().then(data=>({...data,error:''})).catch(e=>({options:[] as MaintenanceAssigneeOption[],failedSources:[] as MaintenanceAssignmentDirectorySource[],error:e?.detail||e?.message||'Assignment directory could not be loaded.'}))]); setItem({ ...listItem, ...detail });setAssignmentOptions(directory.options);setDirectoryFailedSources(directory.failedSources);setDirectoryError(directory.error);setUploadedCompletionAttachmentIds(currentCycleCompletionAttachmentIds(detail)); } catch (e: any) { setError(e?.detail || e?.message || 'This request could not be loaded.'); } finally { setLoading(false); } }, [requestId, listItem]);
  useFocusEffect(useCallback(() => { setLoading(true); load(); }, [load]));

  const estimates = list(item, 'estimates'); const workOrders = list(item, 'workOrders'); const appointments = list(item, 'appointments'); const completions = list(item, 'completions'); const attachments = list(item, 'attachments'); const activityEvents = value(item, 'activityEvents') ?? value(item, 'activities') ?? [];
  const propertyName = friendlyHomeName(item, 'propertyName', 'property', 'Property name unavailable'); const unitName = friendlyHomeName(item, 'unitName', 'unit', 'Unit name unavailable');
  const requestStatus=String(value(item,'status')).toLowerCase();const assignment=value(item,'assignment');const assigned=!!value(assignment,'assignedToType')&&!statusIs(value(assignment,'assignedToType'),'unassigned','0');
  const closed=statusIs(requestStatus,'resolved','4','cancelled','8');const canAcknowledge=statusIs(requestStatus,'reported','0');const canAssign=!closed&&!statusIs(requestStatus,'inprogress','3');const canSubmitEstimate=assigned&&!closed;const hasActiveWorkOrder=workOrders.some(order=>statusIs(order.status,'issued','2','inprogress','4'));const canIssueWorkOrder=assigned&&!closed&&!hasActiveWorkOrder;const confirmationDue=(completion:any)=>new Date(completion.tenantConfirmationDueAtUtc).valueOf()<=Date.now();

  const run = async (action: string, operation: (key: string) => Promise<unknown>, success: string) => { setBusy(true); try { await operation(keyFor(action)); completedAction(action); Alert.alert('Workflow updated', success); await load(); } catch (e: any) { Alert.alert('Could not update workflow', e?.detail || e?.message || 'Refresh and retry. The same retry key will be reused.'); } finally { setBusy(false); } };
  const acknowledge=()=>run('acknowledge',key=>MaintenanceAPI.acknowledge(requestId,key),'Request acknowledged.');
  const assignRequest = () => { const id = number(assigneeId); if (!canAssign) return; if (assigneeType !== 'Self' && !id) return Alert.alert('Assignee required', `Choose a ${assigneeType === 'Vendor' ? 'vendor' : 'team member'}.`); return run(`assign-${assigneeType}-${id}`, key => MaintenanceAPI.assignRequest(requestId, { assignedToType: assigneeType, assignedToUserId: assigneeType === 'OrganizationMember' ? id : null, vendorId: assigneeType === 'Vendor' ? id : null, estimateRequired }, key), 'Assignment saved.'); };
  const submitEstimate = () => { if(!canSubmitEstimate)return;const parsed = number(amount); if (!parsed || parsed <= 0 || scope.trim().length < 3) return Alert.alert('Estimate incomplete', 'Enter a positive amount and scope.'); return run(`estimate-${parsed}-${scope.trim()}`, key => MaintenanceAPI.submitEstimate(requestId, { amount: parsed, currency: 'USD', scope: scope.trim(), validUntilUtc: null }, key), 'Estimate submitted.'); };
  const approveEstimate = (estimate: any) => run(`approve-estimate-${estimate.id}-${estimate.version}`, key => MaintenanceAPI.approveEstimate(requestId, estimate.id, estimate.version, key), 'Estimate approved.');
  const rejectEstimate = (estimate: any) => estimateRejectReason.trim().length < 5 ? Alert.alert('Reason required', 'Enter a rejection reason of at least 5 characters.') : run(`reject-estimate-${estimate.id}-${estimate.version}`, key => MaintenanceAPI.rejectEstimate(requestId, estimate.id, estimate.version, estimateRejectReason.trim(), key), 'Estimate rejected.');
  const issueWorkOrder = (estimate?: any) => { if(!canIssueWorkOrder)return;const workScope = (scope || estimate?.scope || '').trim(); if (workScope.length < 3) return Alert.alert('Scope required', 'Enter the authorized work scope.'); return run(`work-order-${estimate?.id ?? 'direct'}-${workScope}`, key => MaintenanceAPI.issueWorkOrder(requestId, { estimateId: estimate?.id ?? null, scope: workScope, authorizedAmount: estimate?.amount ?? number(amount), dueAtUtc: null }, key), 'Work order issued.'); };

  const cancelAppointment = (appointment: any) => appointmentCancelReason.trim().length < 5 ? Alert.alert('Cancellation reason required', 'Enter at least 5 characters.') : run(`cancel-appointment-${appointment.id}-${appointment.version}`, key => MaintenanceAPI.cancelAppointment(requestId, appointment.id, appointment.version, appointmentCancelReason.trim(), key), 'Appointment cancelled.');
  const startWork = (workOrder: any) => run(`start-work-${workOrder.id}-${workOrder.version}`, key => MaintenanceAPI.startWork(requestId, workOrder.id, workOrder.version, key), 'Work marked in progress.');
  const cancelWorkOrder = (workOrder: any) => workOrderCancelReason.trim().length < 5 ? Alert.alert('Cancellation reason required', 'Enter at least 5 characters.') : run(`cancel-work-order-${workOrder.id}-${workOrder.version}`, key => MaintenanceAPI.cancelWorkOrder(requestId, workOrder.id, workOrder.version, workOrderCancelReason.trim(), key), 'Work order cancelled.');
  const pickCompletionEvidence=async()=>{const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){Alert.alert('Photo access needed','Allow photo access in Settings to add completion evidence.');return;}const evidenceCount=uploadedCompletionAttachmentIds.length+completionMedia.length;if(evidenceCount>=10)return Alert.alert('Evidence limit reached','Up to 10 photos or videos may be attached.');const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images','videos'],allowsMultipleSelection:true,selectionLimit:10-evidenceCount,videoMaxDuration:60,quality:.8,preferredAssetRepresentationMode:ImagePicker.UIImagePickerPreferredAssetRepresentationMode.Compatible});if(result.canceled)return;const selected:LocalMedia[]=[];for(const asset of result.assets){const type=asset.type==='video'?'video':'image';const mimeType=asset.mimeType||(type==='video'?'video/mp4':'image/jpeg');const candidate={uri:asset.uri,fileName:normalizeMaintenanceMediaFileName(asset.fileName,mimeType),mimeType,fileSize:asset.fileSize,type,idempotencyKey:newIdempotencyKey()} as LocalMedia;const issue=validateMaintenanceMedia(candidate,evidenceCount+selected.length);if(issue){Alert.alert('Evidence not added',issue);continue;}selected.push(candidate);}setCompletionMedia(old=>[...old,...selected]);};
  const submitCompletion = async(workOrder: any) => {if(resolutionNotes.trim().length<5)return Alert.alert('Resolution notes required','Describe the completed repair in at least 5 characters.');if(!completionMedia.length&&!uploadedCompletionAttachmentIds.length)return Alert.alert('Completion evidence required','Add at least one validated photo or video of the completed repair.');const action=`complete-${workOrder.id}-${resolutionNotes.trim()}`;setBusy(true);try{const results=await Promise.allSettled(completionMedia.map(media=>MaintenanceAPI.uploadAttachment(requestId,'Completion',media)));const failed=completionMedia.filter((_,index)=>results[index].status==='rejected');const newlyUploaded=results.filter((result):result is PromiseFulfilledResult<MaintenanceAttachment>=>result.status==='fulfilled').map(result=>result.value.id);const allUploadedIds=[...new Set([...uploadedCompletionAttachmentIds,...newlyUploaded])];if(failed.length){setCompletionMedia(failed);setUploadedCompletionAttachmentIds(allUploadedIds);throw new Error(`${failed.length} completion attachment${failed.length===1?'':'s'} failed. ${allUploadedIds.length} uploaded attachment${allUploadedIds.length===1?' is':'s are'} saved; retry only the failed evidence before submitting completion.`);}const completionEvidenceReference=`attachments:${allUploadedIds.join(',')}`;await MaintenanceAPI.submitCompletion(requestId,{workOrderId:workOrder.id,resolutionNotes:resolutionNotes.trim(),completionEvidenceReference,finalCost:number(finalCost)},keyFor(action));completedAction(action);setCompletionMedia([]);setUploadedCompletionAttachmentIds([]);Alert.alert('Workflow updated','Completion submitted for tenant confirmation.');await load();}catch(e:any){Alert.alert('Could not submit completion',e?.detail||e?.message||'Retry with the same evidence. Previously uploaded evidence is retained.');}finally{setBusy(false);}};
  const staffCloseCompletion = (completion: any) => staffCloseReason.trim().length < 5 ? Alert.alert('Close reason required', 'Enter a staff close reason of at least 5 characters.') : run(`staff-close-${completion.id}-${completion.version}`, key => MaintenanceAPI.staffCloseCompletion(requestId, completion.id, completion.version, staffCloseReason.trim(), key), 'Completion closed by staff.');
  const openEvidence = async (attachment: MaintenanceAttachment) => { let uri:string|undefined;setBusy(true); try { uri = await MaintenanceAPI.downloadAttachment(requestId, attachment); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: attachment.contentType, dialogTitle: 'View or save maintenance evidence' }); else Alert.alert('Evidence unavailable','Sharing is not available on this device.'); } catch (e: any) { Alert.alert('Evidence unavailable', e?.detail || e?.message || 'The private file could not be opened.'); } finally { if(uri)await MaintenanceAPI.deleteDownloadedAttachment(uri).catch(()=>undefined);setBusy(false); } };

  if (loading) return <ActivityIndicator style={{ marginTop: 60 }} color="#0b5cab" />;
  if (error) return <View style={s.page}><View style={s.panel}><Text style={s.error}>{error}</Text><Button label="Retry" onPress={load} /></View></View>;
  return <KeyboardAvoidingView style={s.page} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" keyboardDismissMode="interactive" automaticallyAdjustKeyboardInsets={Platform.OS === 'ios'}>
    <TouchableOpacity onPress={() => navigation.goBack()}><Text style={s.link}>‹ Maintenance</Text></TouchableOpacity>
    <Text style={s.eyebrow}>MAINTENANCE REQUEST</Text><Text style={s.title}>{value(item, 'title') || 'Maintenance request'}</Text><Text style={s.status}>{displayStatus(value(item, 'status'))}</Text><Text style={s.body}>{value(item, 'description')}</Text><Text style={s.meta}>{propertyName} · {unitName} · {value(item, 'location') || 'Location not provided'}</Text>{canAcknowledge?<Button label="Acknowledge request" onPress={acknowledge} disabled={busy}/>:null}
    <Section title="Assignment"><Text style={s.body}>Current: {value(value(item, 'assignment'), 'assignedToType') || 'Unassigned'}</Text><View style={s.row}>{(['Self', 'OrganizationMember', 'Vendor'] as const).map(type => <Chip key={type} label={type === 'OrganizationMember' ? 'Team member' : type} active={assigneeType === type} disabled={!canAssign} onPress={() => {setAssigneeType(type);setAssigneeId('');}} />)}</View>{directoryFailedSources.length?<View><Text style={s.error}>Some assignment options could not be loaded ({directoryFailedSources.map(source=>source==='members'?'team members':'vendors').join(' and ')}). The options shown are partial, not an authoritative empty directory.</Text><Small label="Retry assignment directory" onPress={load} disabled={busy}/></View>:directoryError?<View><Text style={s.error}>{directoryError}</Text><Small label="Retry assignment directory" onPress={load} disabled={busy}/></View>:null}{assigneeType !== 'Self' && <View>{assignmentOptions.filter(option=>option.type===assigneeType).map(option=><TouchableOpacity accessibilityRole="radio" accessibilityState={{selected:assigneeId===String(option.id),disabled:!canAssign}} disabled={!canAssign} key={`${option.type}-${option.id}`} style={[s.choice,assigneeId===String(option.id)&&s.choiceOn,!canAssign&&s.disabled]} onPress={()=>setAssigneeId(String(option.id))}><Text style={s.cardTitle}>{option.label}</Text>{option.detail?<Text style={s.muted}>{option.detail}</Text>:null}</TouchableOpacity>)}{!directoryFailedSources.includes(assigneeType==='Vendor'?'vendors':'members')&&!directoryError&&!assignmentOptions.some(option=>option.type===assigneeType)?<Text style={s.muted}>No eligible {assigneeType==='Vendor'?'vendors':'team members'} are available.</Text>:null}</View>}<TouchableOpacity accessibilityRole="checkbox" accessibilityState={{checked:estimateRequired,disabled:!canAssign}} style={[s.check,!canAssign&&s.disabled]} disabled={!canAssign} onPress={() => setEstimateRequired(v => !v)}><Text style={s.body}>{estimateRequired ? '☑' : '☐'} Estimate required</Text></TouchableOpacity><Button label="Save assignment" onPress={assignRequest} disabled={busy||!canAssign||(assigneeType!=='Self'&&!assigneeId)} /></Section>
    <Section title="Estimate & work authorization"><Field value={scope} onChangeText={setScope} placeholder="Scope of work" multiline /><Field value={amount} onChangeText={setAmount} placeholder="Amount (USD)" keyboardType="decimal-pad" inputAccessoryViewID={MONEY_KEYBOARD_ACCESSORY_ID} /><Field value={estimateRejectReason} onChangeText={setEstimateRejectReason} placeholder="Estimate rejection reason" multiline /><Button label="Submit estimate" onPress={submitEstimate} disabled={busy||!canSubmitEstimate} />{estimates.map((estimate: any) => <Card key={estimate.id} title={`Estimate · $${Number(estimate.amount).toFixed(2)}`} detail={`${estimate.scope} · ${String(estimate.status)}`}><View style={s.row}><Small label="Approve" onPress={() => approveEstimate(estimate)} disabled={busy || !statusIs(estimate.status, 'submitted', '2')} /><Small label="Reject" onPress={() => rejectEstimate(estimate)} disabled={busy || !statusIs(estimate.status, 'submitted', '2')} /><Small label="Issue work order" onPress={() => issueWorkOrder(estimate)} disabled={busy || !canIssueWorkOrder || !statusIs(estimate.status, 'approved', '3')} /></View></Card>)}<Button label="Issue work order without estimate" onPress={() => issueWorkOrder()} disabled={busy||!canIssueWorkOrder||!!value(item,'estimateRequired')} /></Section>
    <Section title="Work orders & appointments"><Text style={s.muted}>Appointment scheduling is unavailable in this app version. Appointments can be reviewed and cancelled here.</Text>{appointments.length?<Field value={appointmentCancelReason} onChangeText={setAppointmentCancelReason} placeholder="Appointment cancellation reason" multiline />:null}<Field value={workOrderCancelReason} onChangeText={setWorkOrderCancelReason} placeholder="Work order cancellation reason" multiline />{workOrders.map((order: any) => <Card key={order.id} title="Work order" detail={`${order.scope} · ${String(order.status)} · Due ${date(order.dueAtUtc)}`}><View style={s.row}><Small label="Start work" onPress={() => startWork(order)} disabled={busy || !statusIs(order.status,'issued','2')} /><Small label="Cancel work order" onPress={() => cancelWorkOrder(order)} disabled={busy || !statusIs(order.status,'issued','2')} /><Small label="Submit completion" onPress={() => submitCompletion(order)} disabled={busy || !statusIs(order.status, 'inprogress', '4')} /></View></Card>)}{appointments.map((appointment: any) => <Card key={appointment.id} title="Appointment" detail={`${date(appointment.startsAtUtc)} – ${date(appointment.endsAtUtc)} · ${String(appointment.status)}`}><Small label="Cancel appointment" onPress={() => cancelAppointment(appointment)} disabled={busy || !statusIs(appointment.status, 'proposed', '1','confirmed','2')} /></Card>)}</Section>
    <Section title="Completion & staff close"><Field value={resolutionNotes} onChangeText={setResolutionNotes} placeholder="Completed repair notes" multiline /><Field value={finalCost} onChangeText={setFinalCost} placeholder="Final cost (optional)" keyboardType="decimal-pad" inputAccessoryViewID={MONEY_KEYBOARD_ACCESSORY_ID} /><Field value={staffCloseReason} onChangeText={setStaffCloseReason} placeholder="Staff close reason" multiline /><Button label={`Add completion photo or video (${uploadedCompletionAttachmentIds.length+completionMedia.length})`} onPress={pickCompletionEvidence} disabled={busy||!workOrders.some(order=>statusIs(order.status,'inprogress','4'))||uploadedCompletionAttachmentIds.length+completionMedia.length>=10}/>{uploadedCompletionAttachmentIds.length?<Text style={s.muted}>{uploadedCompletionAttachmentIds.length} current-cycle completion attachment{uploadedCompletionAttachmentIds.length===1?' is':'s are'} already uploaded and restored from this request.</Text>:null}{completions.length ? completions.map((completion: any) => <Card key={completion.id} title={`Completion · ${String(completion.status)}`} detail={`${completion.resolutionNotes} · Tenant response due ${date(completion.tenantConfirmationDueAtUtc)}`}><Small label="Staff close" onPress={() => staffCloseCompletion(completion)} disabled={busy || !statusIs(completion.status,'submitted','1') || !confirmationDue(completion)} /></Card>) : <Text style={s.muted}>No completion has been submitted.</Text>}</Section>
    <Section title="Evidence">{attachments.length ? attachments.map((attachment: MaintenanceAttachment) => <Card key={attachment.id} title={attachment.fileName} detail={`${attachment.contentType} · ${(attachment.sizeBytes / 1024 / 1024).toFixed(1)} MB`}>{preview?.id === attachment.id && attachment.contentType.startsWith('image/') ? <Image source={{ uri: preview.uri }} style={s.image} /> : null}<Small label="View or save private evidence" onPress={() => openEvidence(attachment)} disabled={busy} /></Card>) : <Text style={s.muted}>No evidence attached.</Text>}</Section>
    <Section title="Timeline">{activityEvents.length ? activityEvents.map((event: any, index: number) => <View key={event.id ?? index} style={s.timeline}><Text style={s.cardTitle}>{event.summary || event.title || event.eventType || 'Workflow update'}</Text><Text style={s.muted}>{date(event.occurredAtUtc || event.createdAt)}</Text></View>) : <Text style={s.muted}>No workflow events yet.</Text>}</Section>
  </ScrollView>{Platform.OS === 'ios' ? <InputAccessoryView nativeID={MONEY_KEYBOARD_ACCESSORY_ID}><View style={s.keyboardAccessory}><TouchableOpacity accessibilityRole="button" accessibilityLabel="Done editing amount" onPress={Keyboard.dismiss} style={s.keyboardDone}><Text style={s.keyboardDoneText}>Done</Text></TouchableOpacity></View></InputAccessoryView> : null}</KeyboardAvoidingView>;
}

const Section = ({ title, children }: any) => <View style={s.panel}><Text style={s.section}>{title}</Text>{children}</View>;
const Field = (props: any) => <TextInput {...props} style={[s.input, props.multiline && s.area]} placeholderTextColor="#83919a" textAlignVertical={props.multiline ? 'top' : 'center'} />;
const Button = ({ label, onPress, disabled }: any) => <TouchableOpacity style={[s.button, disabled && s.disabled]} onPress={onPress} disabled={disabled}><Text style={s.buttonText}>{label}</Text></TouchableOpacity>;
const Small = ({ label, onPress, disabled }: any) => <TouchableOpacity style={[s.small, disabled && s.disabled]} onPress={onPress} disabled={disabled}><Text style={s.smallText}>{label}</Text></TouchableOpacity>;
const Chip = ({ label, active, onPress, disabled = false }: any) => <TouchableOpacity accessibilityRole="radio" accessibilityState={{selected:active,disabled}} style={[s.chip, active && s.chipOn, disabled && s.disabled]} onPress={onPress} disabled={disabled}><Text style={[s.chipText, active && s.chipTextOn]}>{label}</Text></TouchableOpacity>;
const Card = ({ title, detail, children }: any) => <View style={s.card}><Text style={s.cardTitle}>{title}</Text><Text style={s.muted}>{detail}</Text>{children}</View>;
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: '#f7f3ee' }, content: { padding: 18, paddingBottom: 55 }, link: { color: '#0b5cab', fontWeight: '900', marginBottom: 12 }, eyebrow: { color: '#c4485d', fontSize: 11, fontWeight: '900', letterSpacing: 1.2 }, title: { color: '#102d43', fontSize: 26, fontWeight: '900', marginTop: 4 }, status: { color: '#0b5cab', fontWeight: '900', marginTop: 7 }, body: { color: '#526874', lineHeight: 20, marginTop: 5 }, meta: { color: '#74848d', marginTop: 9 }, panel: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#d3dde2', padding: 14, marginTop: 15 }, section: { color: '#102d43', fontSize: 18, fontWeight: '900', marginBottom: 9 }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 9 }, input: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#bdcbd3', minHeight: 46, paddingHorizontal: 11, marginTop: 8, color: '#19384c' }, area: { minHeight: 76, paddingTop: 11 }, button: { backgroundColor: '#0b5cab', minHeight: 47, alignItems: 'center', justifyContent: 'center', marginTop: 10 }, buttonText: { color: '#fff', fontWeight: '900' }, small: { borderWidth: 1, borderColor: '#0b5cab', paddingHorizontal: 10, minHeight: 38, alignItems: 'center', justifyContent: 'center', marginTop: 8 }, smallText: { color: '#0b5cab', fontWeight: '900', fontSize: 12 }, disabled: { opacity: 0.4 }, chip: { borderWidth: 1, borderColor: '#bdcbd3', padding: 9 }, chipOn: { backgroundColor: '#163c59' }, chipText: { color: '#526874', fontWeight: '800' }, chipTextOn: { color: '#fff' }, choice: { borderWidth: 1, borderColor: '#bdcbd3', padding: 10, marginTop: 8 }, choiceOn: { borderColor: '#0b5cab', backgroundColor: '#eaf4fb' }, check: { paddingVertical: 8 }, card: { borderTopWidth: 1, borderColor: '#e2e8eb', paddingTop: 11, marginTop: 11 }, cardTitle: { color: '#19384c', fontWeight: '900' }, muted: { color: '#74848d', fontSize: 12, lineHeight: 17, marginTop: 4 }, timeline: { borderLeftWidth: 3, borderColor: '#0b5cab', paddingLeft: 10, paddingBottom: 14 }, image: { width: '100%', height: 210, resizeMode: 'contain', backgroundColor: '#edf1f3', marginTop: 8 }, error: { color: '#9d2940', fontWeight: '800' }, keyboardAccessory: { minHeight: 44, backgroundColor: '#f1f4f6', borderTopWidth: 1, borderTopColor: '#bdcbd3', alignItems: 'flex-end', justifyContent: 'center', paddingHorizontal: 16 }, keyboardDone: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 8 }, keyboardDoneText: { color: '#0b5cab', fontWeight: '900', fontSize: 16 } });
