import type { Metadata } from "next";
import FeatureLandingPage from "@/components/Marketing/FeatureLandingPage";
import { FiClock } from "react-icons/fi";
import { applyOttoSeo } from '@/lib/otto-seo';

export const metadata: Metadata = applyOttoSeo('/rent/custom-late-fees/', {
  title: "Custom Late Fees for Rent Collection | Property Peace",
  description: "Set property-specific late fees, automate rent reminders, and keep overdue balances clear without manual calculations.",
  keywords: "custom late fees, automated late fees, rent collection late fee software, landlord late rent reminders",
  alternates: { canonical: "/rent/custom-late-fees" },
  openGraph: { title: "Custom Late Fees for Rent Collection | Property Peace", description: "Set property-specific late fees, automate rent reminders, and keep overdue balances clear without manual calculations.", type: "website", url: "/rent/custom-late-fees" },
  twitter: { card: "summary_large_image", title: "Custom Late Fees for Rent Collection | Property Peace", description: "Set property-specific late fees, automate rent reminders, and keep overdue balances clear without manual calculations." },
});

export default function Page() {
  return <FeatureLandingPage icon={FiClock} {...page} />;
}

const page = {'canonicalPath': '/rent/custom-late-fees', 'categoryLabel': 'Rent & Accounting', 'categoryHref': '/features/rent-collection', 'eyebrow': 'Rent collection feature', 'title': 'Custom Late Fees That Match Your Lease', 'subtitle': 'Configure late fees once, apply them consistently, and give tenants a clear balance without manual math or awkward follow-ups.', 'primaryCta': 'Automate Late Fees', 'trustItems': ['No credit card required', 'Free for up to 5 units', 'Built for 1–50 units'], 'problemTitle': 'Late rent gets messy fast', 'problemPoints': ['Every lease can have different grace periods, flat fees, or daily fees.', 'Manual calculations create mistakes and tenant confusion.', 'Following up on overdue rent turns into repetitive texts and emails.'], 'solutionTitle': 'Automate late-fee rules and reminders', 'solutionPoints': ['Set late-fee rules that match the terms in each lease.', 'Show tenants a clear balance with rent, fees, and payment history.', 'Send automated reminders before and after rent is due.'], 'steps': [{'title': 'Set the lease rule', 'body': 'Choose grace period, fee type, and property/unit assignment.'}, {'title': 'Track rent status', 'body': 'Property Peace identifies what is paid, unpaid, and overdue.'}, {'title': 'Notify tenants', 'body': 'Automated reminders keep tenants informed without manual chasing.'}], 'featureTitle': 'Late fee automation features', 'features': ['Custom grace periods', 'Flat or recurring late-fee rules', 'Overdue rent status by tenant', 'Automated email and SMS reminders', 'Clear rent balance history', 'Rent roll exports for records'], 'outcomeTitle': 'Collect consistently without conflict', 'outcomes': ['Apply the same rule every time, reducing disputes.', 'Save time by replacing repetitive follow-up messages.', 'Keep tenants informed before balances become bigger problems.', 'See overdue balances without rebuilding a spreadsheet.'], 'related': [{'label': 'Online rent collection', 'href': '/features/rent-collection', 'description': 'A complete rent tracking and reminder workflow.'}, {'label': 'Payment processing', 'href': '/features/payment-processing', 'description': 'Accept online rent payments and track payment history.'}, {'label': 'Rent reporting', 'href': '/rent/rent-reporting', 'description': 'Help tenants understand payment history and on-time habits.'}], 'faqs': [{'question': 'Can late fees vary by property?', 'answer': 'Yes. You can configure rules around the lease or unit so different properties can use different grace periods or fee structures.'}, {'question': 'Are tenants notified automatically?', 'answer': 'Yes. Property Peace supports automated reminders so you do not need to manually chase every overdue balance.'}, {'question': 'Should I verify my local late-fee rules?', 'answer': 'Yes. Late-fee rules vary by lease and jurisdiction, so landlords should make sure their settings match their lease and local requirements.'}]};
