import type { Metadata } from "next";
import FeatureLandingPage from "@/components/Marketing/FeatureLandingPage";
import { FiFile } from "react-icons/fi";
import { applyOttoSeo } from '@/lib/otto-seo';

export const metadata: Metadata = applyOttoSeo('/lease/e-sign-docusign/', {
  title: "DocuSign E-Signatures for Leases | Property Peace",
  description: "Send leases for DocuSign e-signature, track signing status, and store completed lease documents in Property Peace.",
  keywords: "DocuSign lease signing, electronic lease signing, e-sign leases, digital lease management",
  alternates: { canonical: "/lease/e-sign-docusign" },
  openGraph: { title: "DocuSign E-Signatures for Leases | Property Peace", description: "Send leases for DocuSign e-signature, track signing status, and store completed lease documents in Property Peace.", type: "website", url: "/lease/e-sign-docusign" },
  twitter: { card: "summary_large_image", title: "DocuSign E-Signatures for Leases | Property Peace", description: "Send leases for DocuSign e-signature, track signing status, and store completed lease documents in Property Peace." },
});

export default function Page() {
  return <FeatureLandingPage icon={FiFile} {...page} />;
}

const page = {'canonicalPath': '/lease/e-sign-docusign', 'categoryLabel': 'Lease Management', 'categoryHref': '/features/lease-management', 'eyebrow': 'Lease signing feature', 'title': 'E-Sign Leases with DocuSign', 'subtitle': 'Send lease documents for trusted digital signature, track signing progress, and keep final leases organized with the property record.', 'primaryCta': 'Send a Lease for Signing', 'trustItems': ['No credit card required', 'Free for up to 2 units', 'Built for 1–50 units'], 'problemTitle': 'Paper leases slow everything down', 'problemPoints': ['Printing, scanning, and emailing signature pages creates delays.', 'It is easy to lose track of who has signed and who still needs a reminder.', 'Final signed copies end up buried in inboxes instead of property records.'], 'solutionTitle': 'Digital signing keeps renewals moving', 'solutionPoints': ['Send leases electronically through DocuSign workflows.', 'Track envelope and signature status from the lease record.', 'Store completed signed documents with the tenant and property.'], 'steps': [{'title': 'Prepare the document', 'body': 'Start from your lease draft or uploaded lease file.'}, {'title': 'Send for signature', 'body': 'Route the lease to tenants through DocuSign.'}, {'title': 'Track and store', 'body': 'See signature status and keep the completed lease in Property Peace.'}], 'featureTitle': 'E-signing features', 'features': ['DocuSign integration', 'Digital lease envelope tracking', 'Signature status visibility', 'Automatic reminder workflow support', 'Completed document storage', 'Lease renewal organization'], 'outcomeTitle': 'Faster signing, cleaner records', 'outcomes': ['Reduce delays caused by printing and scanning.', 'Know exactly where each lease stands.', 'Keep signed copies connected to the property and tenant.', 'Make renewals easier to manage.'], 'related': [{'label': 'AI lease creation', 'href': '/lease/ai-lease-creation', 'description': 'Draft leases before sending for signature.'}, {'label': 'Lease management', 'href': '/features/lease-management', 'description': 'Manage lease documents, terms, and expirations.'}, {'label': 'Document management', 'href': '/features/document-management', 'description': 'Store leases and property files securely.'}], 'faqs': [{'question': 'Does Property Peace use DocuSign?', 'answer': 'Yes. Lease signing is designed around DocuSign electronic signature workflows.'}, {'question': 'Can I track who has signed?', 'answer': 'Yes. Signature status tracking helps you see what is complete and what still needs attention.'}, {'question': 'Are signed leases stored after completion?', 'answer': 'Yes. Completed documents can be stored with the lease, tenant, and property records.'}], 'disclaimer': 'Electronic signature requirements can vary by document and jurisdiction. Confirm your lease workflow meets your local requirements.'};
