import React from 'react';
import { Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { RouteProp, useNavigation, useRoute } from '@react-navigation/native';
import { MaintenanceStackParamList } from '../../navigation/types';
import { emergencyGuidance } from '../../features/maintenance/maintenanceModel';

type Route = RouteProp<MaintenanceStackParamList,'MaintenanceEmergency'>;
export default function MaintenanceEmergencyScreen(){const navigation=useNavigation<any>();const {signals}=useRoute<Route>().params;return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.alert}>EMERGENCY SAFETY</Text><Text style={s.title}>Protect people first</Text><View style={s.card}><Text style={s.step}>1</Text><Text style={s.copy}>{emergencyGuidance(signals)}</Text></View><View style={s.card}><Text style={s.step}>2</Text><Text style={s.copy}>Do not attempt repairs, investigate the source, or wait for a maintenance response when there is immediate danger.</Text></View><View style={s.card}><Text style={s.step}>3</Text><Text style={s.copy}>After you are safe, return to submit the property report so the property team also receives the issue.</Text></View><TouchableOpacity style={s.call} onPress={()=>Linking.openURL('tel:911')}><Text style={s.callText}>Call 911</Text></TouchableOpacity><Text style={s.note}>Calling 911 uses your phone. Property Peace does not place the emergency call or monitor this screen.</Text><TouchableOpacity style={s.back} onPress={()=>navigation.goBack()}><Text style={s.backText}>I understand — return to report</Text></TouchableOpacity></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#fff5f5'},content:{padding:22,paddingBottom:50},alert:{fontSize:12,fontWeight:'900',letterSpacing:1.5,color:'#a21e35'},title:{fontSize:31,fontWeight:'900',color:'#501522',marginTop:6,marginBottom:18},card:{flexDirection:'row',gap:13,backgroundColor:'#fff',borderWidth:1,borderColor:'#e4a8b2',padding:15,marginBottom:10,borderRadius:3},step:{width:28,height:28,textAlign:'center',paddingTop:4,backgroundColor:'#a21e35',color:'#fff',fontWeight:'900'},copy:{flex:1,color:'#3c2830',fontSize:15,lineHeight:22,fontWeight:'700'},call:{minHeight:58,backgroundColor:'#a21e35',alignItems:'center',justifyContent:'center',marginTop:12,borderRadius:3},callText:{color:'#fff',fontSize:19,fontWeight:'900'},note:{fontSize:12,lineHeight:18,color:'#725e65',marginVertical:12},back:{minHeight:52,borderWidth:2,borderColor:'#501522',alignItems:'center',justifyContent:'center',borderRadius:3},backText:{fontWeight:'900',color:'#501522'}});
