import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { RouteProp, useNavigation, useRoute } from '@react-navigation/native';
import { MaintenanceStackParamList } from '../../navigation/types';
import MaintenanceAPI, { LocalMedia } from '../../api/maintenanceAPI';
import { displayStatus } from '../../features/maintenance/maintenanceModel';

type Route=RouteProp<MaintenanceStackParamList,'TenantMaintenanceReceipt'>;
const date=(value?:string)=>value?new Date(value).toLocaleString():'Not available';
export default function TenantMaintenanceReceiptScreen(){
 const navigation=useNavigation<any>();const params=useRoute<Route>().params;const {request}=params;const id=request.id??request.Id;
 const initialStatus=String(request.status??request.Status??'').toLowerCase();const [failedMedia,setFailedMedia]=useState<LocalMedia[]>(params.failedMedia??[]);const [retrying,setRetrying]=useState(false);const [retryStage,setRetryStage]=useState<'allowed'|'closed'|'unknown'|'checking'>(['reported','0'].includes(initialStatus)?'allowed':initialStatus?'closed':'unknown');
 const refreshRetryStage=async():Promise<'allowed'|'closed'|'unknown'>=>{setRetryStage('checking');try{const latest=await MaintenanceAPI.getDetail(id);const stage=['reported','0'].includes(String(latest.status??latest.Status).toLowerCase())?'allowed':'closed';setRetryStage(stage);return stage;}catch{setRetryStage('unknown');return 'unknown';}};
 useEffect(()=>{if(failedMedia.length)void refreshRetryStage();},[]);
 const uploadFailed=async()=>{setRetrying(true);const results=await Promise.allSettled(failedMedia.map(media=>MaintenanceAPI.uploadAttachment(id,'Intake',media)));const remaining=failedMedia.filter((_,index)=>results[index]?.status==='rejected');setFailedMedia(remaining);setRetrying(false);Alert.alert(remaining.length?'Some evidence still needs attention':'Evidence uploaded',remaining.length?`${remaining.length} attachment${remaining.length===1?'':'s'} still could not be uploaded. Refresh status or retry again.`:'All evidence is now attached to your request.');};
 const retryUploads=async()=>{if(!failedMedia.length||retrying)return;const stage=await refreshRetryStage();if(stage==='closed'){Alert.alert('Evidence stage closed','Evidence can only be added while the report is still newly reported. The request and its existing evidence are safe; contact your property team if another file is essential.');return;}if(stage==='unknown'){Alert.alert('Status could not be verified','The network did not confirm whether intake evidence is still open. Your report is safe. You can refresh status or make an honest upload attempt; the server will reject it if the stage has closed.',[{text:'Cancel',style:'cancel'},{text:'Refresh status',onPress:()=>void refreshRetryStage()},{text:'Retry upload anyway',onPress:()=>void uploadFailed()}]);return;}await uploadFailed();};
 return <ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.check}><Text style={s.checkText}>✓</Text></View><Text style={s.eyebrow}>REPORT RECEIVED</Text><Text style={s.title}>Your request is on record</Text><Text style={s.body}>Status and timeline updates will remain available in Maintenance.</Text><View style={s.receipt}><Row label="Issue" value={String(request.title??request.Title??'Maintenance request')}/><Row label="Home" value={String(request.unitName??request.UnitName??request.propertyName??request.PropertyName??request.location??request.Location??'Your home')}/><Row label="Submitted" value={date(request.createdAtUtc??request.CreatedAtUtc)}/><Row label="Status" value={displayStatus(request.status??request.Status)}/><Row label="Triage" value={String(request.urgency??request.Urgency??'Routine')}/><Row label="Acknowledge by" value={date(request.acknowledgeByUtc??request.AcknowledgeByUtc)}/><Row label="Action target" value={date(request.actionByUtc??request.ActionByUtc)}/></View>{failedMedia.length>0&&<View style={s.warning}><Text style={s.warningText}>{retryStage==='allowed'?`${failedMedia.length} attachment${failedMedia.length===1?'':'s'} could not be uploaded. Your report is safe; retry the evidence now.`:retryStage==='closed'?'Evidence can only be added while the report is still newly reported. This request has moved forward, so retry is disabled.':retryStage==='checking'?'Checking whether evidence can still be added…':'The request status could not be refreshed. This does not mean evidence is frozen; refresh status or try the upload and let the server decide.'}</Text><TouchableOpacity style={[s.retry,retryStage==='closed'&&{opacity:.45}]} onPress={retryUploads} disabled={retrying||retryStage==='closed'||retryStage==='checking'}>{retrying||retryStage==='checking'?<ActivityIndicator color="#0b5cab"/>:<Text style={s.retryText}>Retry evidence upload</Text>}</TouchableOpacity>{retryStage==='unknown'?<TouchableOpacity style={s.retry} onPress={()=>void refreshRetryStage()}><Text style={s.retryText}>Refresh status</Text></TouchableOpacity>:null}</View>}<Text style={s.note}>Targets are service goals shown by the API, not appointment guarantees. Emergency reports do not replace calling 911.</Text><TouchableOpacity style={s.primary} onPress={()=>navigation.replace('TenantMaintenanceDetail',{requestId:String(id),listItem:request})}><Text style={s.primaryText}>View request and timeline</Text></TouchableOpacity><TouchableOpacity style={s.secondary} onPress={()=>navigation.navigate('TenantMaintenanceList')}><Text style={s.secondaryText}>Back to maintenance</Text></TouchableOpacity></ScrollView>;
}
const Row=({label,value}:{label:string;value:string})=><View style={s.row}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>;
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f7f3ee'},content:{padding:22,paddingBottom:50},check:{width:54,height:54,backgroundColor:'#24733a',alignItems:'center',justifyContent:'center',borderRadius:3},checkText:{fontSize:30,color:'#fff',fontWeight:'900'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.4,color:'#24733a',marginTop:18},title:{fontSize:28,fontWeight:'900',color:'#102d43',marginVertical:5},body:{fontSize:14,lineHeight:21,color:'#5c6e79'},receipt:{borderWidth:1,borderColor:'#cbd6dc',backgroundColor:'#fff',marginTop:20},row:{padding:13,borderBottomWidth:1,borderColor:'#e2e7ea'},label:{fontSize:11,fontWeight:'900',color:'#71818b',textTransform:'uppercase'},value:{fontSize:15,fontWeight:'800',color:'#19384c',marginTop:4},note:{fontSize:12,lineHeight:18,color:'#71818b',marginTop:13},warning:{backgroundColor:'#fff2d9',borderWidth:1,borderColor:'#e5c078',padding:12,marginTop:12},warningText:{color:'#684a12',lineHeight:19},retry:{minHeight:42,justifyContent:'center',alignItems:'center',borderWidth:1,borderColor:'#0b5cab',backgroundColor:'#fff',marginTop:10},retryText:{color:'#0b5cab',fontWeight:'900'},primary:{minHeight:54,backgroundColor:'#0b5cab',alignItems:'center',justifyContent:'center',marginTop:24,borderRadius:3},primaryText:{color:'#fff',fontWeight:'900',fontSize:16},secondary:{minHeight:50,alignItems:'center',justifyContent:'center'},secondaryText:{color:'#0b5cab',fontWeight:'900'}});
