import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { useNavigation } from '@react-navigation/native';
import MaintenanceAPI, { LocalMedia, newIdempotencyKey } from '../../api/maintenanceAPI';
import { CATEGORIES, emergencyGuidance, isEmergency, MaintenanceCategory, MaintenanceSignal, normalizeMaintenanceMediaFileName, SIGNAL_OPTIONS, validateMaintenanceMedia } from '../../features/maintenance/maintenanceModel';

const field = (x: any, ...keys: string[]) => keys.map(k => x?.[k]).find(v => v !== undefined && v !== null);
const homeLabel = (home: any) => { const property = field(home,'propertyName','PropertyName') ?? field(home?.property,'name','Name') ?? field(home?.Property,'name','Name') ?? 'Property name unavailable'; const unit = field(home,'unitName','UnitName') ?? field(home?.unit,'name','Name','unitNumber','UnitNumber') ?? field(home?.Unit,'name','Name','unitNumber','UnitNumber') ?? 'Unit name unavailable'; return `${property} · ${unit}`; };

export default function TenantMaintenanceIntakeScreen() {
 const navigation=useNavigation<any>(); const [leases,setLeases]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [scope,setScope]=useState(''); const [category,setCategory]=useState<MaintenanceCategory>('Plumbing'); const [location,setLocation]=useState(''); const [description,setDescription]=useState(''); const [signals,setSignals]=useState<MaintenanceSignal[]>([]); const [access,setAccess]=useState<'yes'|'contact'>('contact'); const [pets,setPets]=useState<'none'|'yes'>('none'); const [petDetails,setPetDetails]=useState(''); const [media,setMedia]=useState<LocalMedia[]>([]); const [review,setReview]=useState(false); const [saving,setSaving]=useState(false);
 const createKey=useRef(newIdempotencyKey());
 useEffect(()=>{ MaintenanceAPI.getTenantLeaseScopes().then(x=>{setLeases(x);setScope(x.length===1?String(field(x[0],'id','Id')):'');}).catch(()=>Alert.alert('Lease unavailable','We could not load your active homes.')).finally(()=>setLoading(false)); },[]);
 const lease=leases.find(x=>String(field(x,'id','Id'))===scope); const propertyId=Number(field(lease,'propertyId','PropertyId') ?? field(lease?.property,'id','Id') ?? field(lease?.Property,'id','Id')); const unitId=Number(field(lease,'unitId','UnitId') ?? field(lease?.unit,'id','Id') ?? field(lease?.Unit,'id','Id')); const selectedHomeLabel=lease?homeLabel(lease):'No home selected'; const emergency=useMemo(()=>isEmergency(signals),[signals]);
 const toggleSignal=(s:MaintenanceSignal)=>setSignals(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s]);
 const addAssets=(assets:ImagePicker.ImagePickerAsset[])=>{ const next:LocalMedia[]=[]; for(const a of assets){ const type=a.type==='video'?'video':'image'; const mimeType=a.mimeType || (type==='video'?'video/mp4':'image/jpeg'); const candidate={uri:a.uri,fileName:normalizeMaintenanceMediaFileName(a.fileName,mimeType),mimeType,fileSize:a.fileSize,type,idempotencyKey:newIdempotencyKey()} as LocalMedia;const issue=validateMaintenanceMedia(candidate,media.length+next.length);if(issue){Alert.alert('File not added',issue);continue;}next.push(candidate);}setMedia(old=>[...old,...next]); };
 const library=async()=>{ const p=await ImagePicker.requestMediaLibraryPermissionsAsync(); if(!p.granted){Alert.alert('Photo access needed','Allow photo access in Settings to attach maintenance evidence.');return;} const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images','videos'],allowsMultipleSelection:true,selectionLimit:10-media.length,videoMaxDuration:60,quality:.8,preferredAssetRepresentationMode:ImagePicker.UIImagePickerPreferredAssetRepresentationMode.Compatible}); if(!r.canceled)addAssets(r.assets); };
 const camera=async()=>{ const p=await ImagePicker.requestCameraPermissionsAsync(); if(!p.granted){Alert.alert('Camera access needed','Allow camera access in Settings to take maintenance evidence.');return;} const r=await ImagePicker.launchCameraAsync({mediaTypes:['images','videos'],videoMaxDuration:60,quality:.8}); if(!r.canceled)addAssets(r.assets); };
 const validate=()=>{if(!propertyId||!unitId)return 'An active leased unit is required.';if(!location.trim())return 'Enter the exact location.';if(description.trim().length<10)return 'Describe the issue in at least 10 characters.';if(pets==='yes'&&!petDetails.trim())return 'Add pet details for safe entry.';return '';};
 const submit=async()=>{const issue=validate();if(issue){Alert.alert('Check your report',issue);return;}setSaving(true);try{const instructions=`Entry: ${access==='yes'?'Permission granted':'Contact tenant first'}. Pets: ${pets==='yes'?petDetails.trim():'None reported'}.`;const created=await MaintenanceAPI.createTenantRequest({propertyId,unitId,title:category,description:`${description.trim()}\n\n${instructions}`,location:location.trim(),signals,hasPhotos:media.some(x=>x.type==='image'),preferredWindows:[]},createKey.current);createKey.current=newIdempotencyKey();const id=created.id??created.Id;const uploads=await Promise.allSettled(media.map(m=>MaintenanceAPI.uploadAttachment(id,'Intake',m)));const failedMedia=media.filter((_,index)=>uploads[index]?.status==='rejected');const failed=failedMedia.length;navigation.replace('TenantMaintenanceReceipt',{request:created,failedMedia,uploadWarning:failed?`${failed} attachment${failed===1?'':'s'} could not be uploaded.`:undefined});}catch(e:any){Alert.alert('Could not submit',e?.detail||e?.message||'Please try again.');}finally{setSaving(false);}};
 if(loading)return <ActivityIndicator style={{marginTop:60}} color="#0b5cab"/>;
 if(review)return <KeyboardSafePage><Text style={s.eyebrow}>REVIEW</Text><Text style={s.heading}>Check your report</Text>{emergency&&<View style={s.danger}><Text style={s.dangerTitle}>Emergency safety guidance</Text><Text style={s.body}>{emergencyGuidance(signals)}</Text><Text style={s.bold}>Submitting does not contact 911.</Text></View>}<Summary label="Home" value={selectedHomeLabel}/><Summary label="Issue" value={`${category} · ${location}\n${description}`}/><Summary label="Severity signals" value={signals.length?signals.join(', '):'None selected'}/><Summary label="Access" value={`${access==='yes'?'Permission granted':'Contact me first'} · ${pets==='yes'?petDetails:'No pets reported'}`}/><Summary label="Evidence" value={`${media.length} photo/video attachment${media.length===1?'':'s'}`}/><TouchableOpacity style={s.primary} onPress={submit} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Submit maintenance report</Text>}</TouchableOpacity><TouchableOpacity style={s.secondary} onPress={()=>setReview(false)}><Text style={s.secondaryText}>Back to edit</Text></TouchableOpacity></KeyboardSafePage>;
 return <KeyboardSafePage><Text style={s.eyebrow}>STRUCTURED REPORT</Text><Text style={s.heading}>What needs attention?</Text><Text style={s.body}>Clear details help your property team act safely and quickly.</Text>
 <Label text="Home"/><Text style={s.hint}>{leases.length>1?'Select the affected home. This choice determines which landlord receives the report.':'Confirm the affected home.'}</Text><View style={s.wrap}>{leases.map(home=>{const id=String(field(home,'id','Id'));return <Chip key={id} text={homeLabel(home)} active={scope===id} onPress={()=>setScope(id)}/>;})}</View>{!leases.length?<View style={s.box}><Text style={s.bold}>No active lease found</Text></View>:null}
 <Label text="Category"/><View style={s.wrap}>{CATEGORIES.map(x=><Chip key={x} text={x} active={category===x} onPress={()=>setCategory(x)}/>)}</View><Label text="Exact location"/><TextInput style={s.input} value={location} onChangeText={setLocation} placeholder="Kitchen, under the sink"/><Label text="Describe what is happening"/><TextInput style={[s.input,s.area]} multiline value={description} onChangeText={setDescription} placeholder="What can you see, hear, or smell? When did it start?" textAlignVertical="top"/>
 <Label text="Safety and severity signals"/><Text style={s.hint}>Select every condition that applies. This deterministic checklist—not AI—triggers emergency guidance.</Text>{SIGNAL_OPTIONS.map(x=><TouchableOpacity accessibilityRole="checkbox" accessibilityState={{checked:signals.includes(x.value)}} key={x.value} style={[s.check,signals.includes(x.value)&&s.checkOn,x.emergency&&signals.includes(x.value)&&s.checkDanger]} onPress={()=>toggleSignal(x.value)}><Text style={s.checkMark}>{signals.includes(x.value)?'✓':'○'}</Text><Text style={s.bold}>{x.label}</Text></TouchableOpacity>)}{emergency&&<TouchableOpacity style={s.danger} onPress={()=>navigation.navigate('MaintenanceEmergency',{signals})}><Text style={s.dangerTitle}>Immediate safety steps required →</Text><Text style={s.body}>{emergencyGuidance(signals)}</Text></TouchableOpacity>}
 <Label text="Entry permission"/><View style={s.wrap}><Chip text="Permission to enter" active={access==='yes'} onPress={()=>setAccess('yes')}/><Chip text="Contact me first" active={access==='contact'} onPress={()=>setAccess('contact')}/></View><Label text="Pets"/><View style={s.wrap}><Chip text="No pets" active={pets==='none'} onPress={()=>setPets('none')}/><Chip text="Pets in home" active={pets==='yes'} onPress={()=>setPets('yes')}/></View>{pets==='yes'&&<TextInput style={s.input} value={petDetails} onChangeText={setPetDetails} placeholder="Type, location, and entry precautions"/>}
 <Label text="Photos or video (up to 10)"/><View style={s.mediaButtons}><TouchableOpacity style={s.secondarySmall} onPress={camera}><Text style={s.secondaryText}>Use camera</Text></TouchableOpacity><TouchableOpacity style={s.secondarySmall} onPress={library}><Text style={s.secondaryText}>Choose library</Text></TouchableOpacity></View><ScrollView horizontal>{media.map((m,i)=><View key={`${m.uri}-${i}`} style={s.preview}>{m.type==='image'?<Image source={{uri:m.uri}} style={s.image}/>:<View style={[s.image,s.video]}><Text style={s.bold}>VIDEO</Text></View>}<TouchableOpacity onPress={()=>setMedia(v=>v.filter((_,n)=>n!==i))}><Text style={s.remove}>Remove</Text></TouchableOpacity></View>)}</ScrollView>
 <TouchableOpacity style={s.primary} onPress={()=>{const e=validate();e?Alert.alert('Check your report',e):setReview(true);}}><Text style={s.primaryText}>Review report</Text></TouchableOpacity></KeyboardSafePage>;
}
const KeyboardSafePage=({children}:{children:React.ReactNode})=><KeyboardAvoidingView style={s.page} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" keyboardDismissMode="interactive" automaticallyAdjustKeyboardInsets={Platform.OS === 'ios'}>{children}</ScrollView></KeyboardAvoidingView>;
const Label=({text}:{text:string})=><Text style={s.label}>{text}</Text>; const Chip=({text,active,onPress}:{text:string;active:boolean;onPress:()=>void})=><TouchableOpacity accessibilityRole="radio" accessibilityState={{selected:active}} style={[s.chip,active&&s.chipOn]} onPress={onPress}><Text style={[s.chipText,active&&s.chipTextOn]}>{text}</Text></TouchableOpacity>; const Summary=({label,value}:{label:string;value:string})=><View style={s.summary}><Text style={s.label}>{label}</Text><Text style={s.body}>{value}</Text></View>;
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f7f3ee'},content:{padding:20,paddingBottom:50},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.3,color:'#c4485d'},heading:{fontSize:26,fontWeight:'900',color:'#102d43',marginVertical:4},body:{color:'#536874',fontSize:14,lineHeight:20},bold:{fontWeight:'800',color:'#19384c',lineHeight:20},muted:{color:'#71818b',marginTop:4},label:{fontWeight:'900',color:'#19384c',fontSize:14,marginTop:20,marginBottom:7},hint:{fontSize:12,lineHeight:17,color:'#71818b',marginBottom:8},box:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d3dde2',borderRadius:4,padding:14},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#cbd7dd',borderRadius:4,padding:13,fontSize:15,color:'#19384c'},area:{height:130},wrap:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:'#bdcbd3',backgroundColor:'#fff',paddingHorizontal:12,paddingVertical:10,borderRadius:3},chipOn:{backgroundColor:'#163c59',borderColor:'#163c59'},chipText:{fontWeight:'800',color:'#536874'},chipTextOn:{color:'#fff'},check:{flexDirection:'row',gap:9,alignItems:'center',padding:12,backgroundColor:'#fff',borderWidth:1,borderColor:'#d3dde2',marginBottom:6,borderRadius:3},checkOn:{borderColor:'#0b5cab',backgroundColor:'#eef6fd'},checkDanger:{borderColor:'#c4485d',backgroundColor:'#fff0f1'},checkMark:{fontSize:19,color:'#0b5cab'},danger:{backgroundColor:'#fff0f1',borderWidth:2,borderColor:'#c4485d',padding:14,marginTop:12,borderRadius:3},dangerTitle:{fontWeight:'900',fontSize:16,color:'#8c2437',marginBottom:5},mediaButtons:{flexDirection:'row',gap:8},secondarySmall:{flex:1,padding:12,alignItems:'center',borderWidth:1,borderColor:'#0b5cab',backgroundColor:'#fff',borderRadius:3},secondaryText:{color:'#0b5cab',fontWeight:'900'},preview:{width:112,marginTop:12,marginRight:10,backgroundColor:'#fff',padding:5,borderWidth:1,borderColor:'#d3dde2'},image:{width:100,height:80},video:{alignItems:'center',justifyContent:'center',backgroundColor:'#e4e9ec'},remove:{textAlign:'center',padding:6,color:'#a52e42',fontWeight:'800'},primary:{minHeight:54,backgroundColor:'#0b5cab',alignItems:'center',justifyContent:'center',marginTop:24,borderRadius:4},primaryText:{color:'#fff',fontSize:16,fontWeight:'900'},secondary:{minHeight:50,alignItems:'center',justifyContent:'center'},summary:{backgroundColor:'#fff',borderBottomWidth:1,borderColor:'#d9e0e4',padding:14},});
