import React, { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import MaintenanceAPI, { MaintenanceRequest } from '../../api/maintenanceAPI';
import { displayStatus, isClosedStatus } from '../../features/maintenance/maintenanceModel';

const value = (item: any, key: string) => item?.[key] ?? item?.[key[0].toUpperCase() + key.slice(1)];
export default function TenantMaintenanceScreen() {
  const navigation = useNavigation<any>();
  const [tab, setTab] = useState<'current' | 'history'>('current');
  const [items, setItems] = useState<MaintenanceRequest[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setError(''); setItems(tab === 'current' ? await MaintenanceAPI.getCurrent(true) : await MaintenanceAPI.getHistory(true)); } catch (e: any) { setItems([]); setError(e?.detail || e?.message || 'Maintenance could not be loaded.'); } finally { setLoading(false); setRefreshing(false); } }, [tab]);
  useFocusEffect(useCallback(() => { setLoading(true); load(); }, [load]));
  return <View style={styles.page}>
    <View style={styles.hero}><Text style={styles.eyebrow}>YOUR HOME</Text><Text style={styles.heading}>Repairs & maintenance</Text><Text style={styles.sub}>Report an issue, see who is handling it, and follow every update.</Text></View>
    <TouchableOpacity accessibilityRole="button" style={styles.newButton} onPress={() => navigation.navigate('TenantMaintenanceIntake')}><Text style={styles.newText}>+ Report an issue</Text></TouchableOpacity>
    <View style={styles.tabs}>{(['current', 'history'] as const).map((name) => <TouchableOpacity key={name} style={[styles.tab, tab === name && styles.tabActive]} onPress={() => setTab(name)}><Text style={[styles.tabText, tab === name && styles.tabTextActive]}>{name === 'current' ? 'Current' : 'History'}</Text></TouchableOpacity>)}</View>
    {loading ? <ActivityIndicator style={{ marginTop: 40 }} color="#0b5cab" /> : <FlatList data={items} keyExtractor={(x, i) => String(value(x, 'id') ?? i)} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} />} contentContainerStyle={styles.list}
      ListHeaderComponent={error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text><TouchableOpacity onPress={load}><Text style={styles.retry}>Try again</Text></TouchableOpacity></View> : null}
      ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>{tab === 'current' ? 'No open repairs' : 'No repair history'}</Text><Text style={styles.sub}>{tab === 'current' ? 'When something needs attention, start a structured report here.' : 'Completed and cancelled requests will appear here.'}</Text></View>}
      renderItem={({ item }) => { const status = value(item, 'status'); return <TouchableOpacity style={styles.card} onPress={() => navigation.navigate('TenantMaintenanceDetail', { requestId: String(value(item, 'id')), listItem: item })}>
        <View style={styles.cardTop}><Text style={styles.cardTitle} numberOfLines={2}>{value(item, 'title') || 'Maintenance request'}</Text><View style={[styles.badge, isClosedStatus(status) && styles.badgeClosed]}><Text style={styles.badgeText}>{displayStatus(status)}</Text></View></View>
        <Text style={styles.description} numberOfLines={2}>{value(item, 'description')}</Text><Text style={styles.meta}>{value(item, 'unitName') || value(item, 'location') || 'Your unit'}  ·  Tap for timeline</Text>
      </TouchableOpacity>; }} />}
  </View>;
}
const styles = StyleSheet.create({ page:{flex:1,backgroundColor:'#f7f3ee'},hero:{padding:20,paddingBottom:12},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.4,color:'#c4485d'},heading:{fontSize:27,fontWeight:'900',color:'#102d43',marginTop:3},sub:{fontSize:14,lineHeight:20,color:'#60717e',marginTop:5},newButton:{marginHorizontal:20,minHeight:52,backgroundColor:'#0b5cab',borderRadius:5,alignItems:'center',justifyContent:'center'},newText:{color:'#fff',fontWeight:'900',fontSize:16},tabs:{flexDirection:'row',margin:16,marginBottom:4,borderWidth:1,borderColor:'#ccd6dd',borderRadius:4,overflow:'hidden'},tab:{flex:1,padding:11,alignItems:'center',backgroundColor:'#fff'},tabActive:{backgroundColor:'#102d43'},tabText:{fontWeight:'800',color:'#516573'},tabTextActive:{color:'#fff'},list:{padding:16,paddingBottom:36},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d7dfe4',borderRadius:5,padding:15,marginBottom:10},cardTop:{flexDirection:'row',alignItems:'flex-start',gap:8},cardTitle:{flex:1,fontSize:16,fontWeight:'900',color:'#173449'},description:{color:'#5e707c',lineHeight:19,marginTop:8},meta:{fontSize:12,color:'#778794',marginTop:10,fontWeight:'700'},badge:{backgroundColor:'#fff0d7',borderWidth:1,borderColor:'#efc56e',borderRadius:3,paddingHorizontal:7,paddingVertical:4},badgeClosed:{backgroundColor:'#e8f5eb',borderColor:'#9dcca6'},badgeText:{fontSize:10,fontWeight:'900',color:'#29475c'},empty:{alignItems:'center',padding:36},emptyTitle:{fontSize:18,fontWeight:'900',color:'#173449'},error:{backgroundColor:'#fff0f1',borderWidth:1,borderColor:'#e0a4ad',padding:12,marginBottom:12},errorText:{color:'#8d2e3d'},retry:{color:'#0b5cab',fontWeight:'900',marginTop:7} });
