import { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import {
  Box,
  Container,
  Typography,
  Button,
  Stack,
  Divider,
  TextField,
  FormControl,
  FormLabel,
  RadioGroup,
  FormControlLabel,
  Radio,
  CircularProgress,
  useTheme,
  alpha
} from '@mui/material';
import MainCard from 'components/MainCard';
import BuildLeaseAgreementHeader from 'sections/landlord/lease-builder/BuildLeaseAgreementHeader';
import { openSnackbar } from 'api/snackbar';
import useFetchProperties from 'hooks/useFetchProperties';
import { selectProperties } from 'store/property/property.selector';
import { updateLease, updateLeaseAgreement } from 'store/lease/lease.action';
import { FileTextOutlined, BookOutlined, BgColorsOutlined, FolderOpenOutlined, CloudUploadOutlined, InfoCircleOutlined } from '@ant-design/icons';

const DEFAULT_EARLY_TERMINATION_CLAUSE = `Either party, upon 60 days' advance written notice to the other party, may terminate this lease early. Termination will be effective as of the last day of the calendar month following the end of the 60 day notice period. Each party understands that a notice of termination can happen at any time after lease signing. Tenant may terminate this lease provided that the Tenant pays a termination fee equal to one months' rent or the maximum allowable by law, whichever is less. Termination charge will be in addition to all rent due and late fees up to the termination date.`;

const FEDERAL_LEAD_PAMPHLET_TEXT =
  'Federal Pamphlet: We will automatically attach the Protect Your Family From Lead In Your Home pamphlet that the federal government requires you give to tenants when the home was built before 1978.';

const LEAD_PAINT_RECORDS_GUIDANCE =
  'Please list the records and/or reports below. For example: On 05/23/1991 there was a report generated by the ABC Company Ltd. that showed evidence of lead-based paint. Remember to share a copy of the records / reports with your tenants.';

const PROPERTY_CONDITION_REPORTS_TEXT =
  'While many states do not require a Property Condition Report form at the beginning of a lease term, it is a good idea to complete one at the beginning of the lease term so any resulting damages at the end of the lease term are properly documented.';

export default function ProvisionsAttachmentsPage({ embedded = false, onSaved } = {}) {
  const theme = useTheme();
  const navigate = useNavigate();
  const dispatch = useDispatch();
  const [searchParams] = useSearchParams();
  const properties = useSelector(selectProperties);
  const { propertiesRefetch } = useFetchProperties();

  const leaseId = searchParams.get('leaseId') ? parseInt(searchParams.get('leaseId')) : null;
  const propertyId = searchParams.get('propertyId') ? parseInt(searchParams.get('propertyId')) : null;
  const unitId = searchParams.get('unitId') ? parseInt(searchParams.get('unitId')) : null;

  const [lease, setLease] = useState(null);
  const [property, setProperty] = useState(null);
  const [unit, setUnit] = useState(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const [includeEarlyTerminationClause, setIncludeEarlyTerminationClause] = useState(false);
  const [earlyTerminationClauseText, setEarlyTerminationClauseText] = useState(DEFAULT_EARLY_TERMINATION_CLAUSE);
  const [additionalTerms, setAdditionalTerms] = useState('');
  const [builtBefore1978, setBuiltBefore1978] = useState(null);
  const [awareOfLeadPaint, setAwareOfLeadPaint] = useState(null);
  const [leadPaintExplanation, setLeadPaintExplanation] = useState('');
  const [hasLeadPaintRecords, setHasLeadPaintRecords] = useState(null);
  const [leadPaintRecordsExplanation, setLeadPaintRecordsExplanation] = useState('');

  const [leadPaintExplanationError, setLeadPaintExplanationError] = useState('');
  const [leadPaintRecordsExplanationError, setLeadPaintRecordsExplanationError] = useState('');

  useEffect(() => {
    const loadData = async () => {
      if (!leaseId || !propertyId) {
        setLoading(false);
        return;
      }
      const foundProperty = properties?.find((p) => p.id === propertyId);
      if (!foundProperty) {
        setLoading(false);
        return;
      }
      setProperty(foundProperty);
      const targetUnit = unitId
        ? foundProperty.units?.find((u) => u.id === unitId)
        : foundProperty.units?.[0];
      if (targetUnit) {
        setUnit(targetUnit);
        const unitLease = targetUnit.lease || targetUnit.Lease;
        if (unitLease && (unitLease.id === leaseId || unitLease.Id === leaseId)) {
          setLease(unitLease);
          setIncludeEarlyTerminationClause(unitLease.includeEarlyTerminationClause ?? unitLease.IncludeEarlyTerminationClause ?? false);
          setEarlyTerminationClauseText(
            unitLease.earlyTerminationClauseText ?? unitLease.EarlyTerminationClauseText ?? DEFAULT_EARLY_TERMINATION_CLAUSE
          );
          setAdditionalTerms(unitLease.additionalTerms ?? unitLease.AdditionalTerms ?? '');
          setBuiltBefore1978(unitLease.builtBefore1978 ?? unitLease.BuiltBefore1978 ?? null);
          setAwareOfLeadPaint(unitLease.awareOfLeadPaint ?? unitLease.AwareOfLeadPaint ?? null);
          setLeadPaintExplanation(unitLease.leadPaintExplanation ?? unitLease.LeadPaintExplanation ?? '');
          setHasLeadPaintRecords(unitLease.hasLeadPaintRecords ?? unitLease.HasLeadPaintRecords ?? null);
          setLeadPaintRecordsExplanation(unitLease.leadPaintRecordsExplanation ?? unitLease.LeadPaintRecordsExplanation ?? '');
        }
      }
      setLoading(false);
    };
    if (properties && properties.length >= 0) loadData();
  }, [leaseId, propertyId, unitId, properties]);

  useEffect(() => {
    if (leaseId && propertyId) propertiesRefetch();
  }, [leaseId, propertyId, propertiesRefetch]);

  const handleBack = () => {
    if (embedded) {
      onSaved?.();
      return;
    }
    navigate(`/landlord/leases/build-lease-agreement?leaseId=${leaseId}&propertyId=${propertyId}${unitId ? `&unitId=${unitId}` : ''}`);
  };

  const buildUpdatePayload = (currentLeaseId) => ({
    id: currentLeaseId,
    propertyId: property?.id || propertyId,
    unitId: unit?.id || unitId,
    name: lease?.name || lease?.Name,
    startDate: lease?.startDate || lease?.StartDate,
    endDate: lease?.endDate || lease?.EndDate,
    rentAmount: lease?.rentAmount ?? lease?.RentAmount,
    depositAmount: lease?.depositAmount ?? lease?.DepositAmount,
    leaseLength: lease?.leaseLength ?? lease?.LeaseLength,
    rentFrequency: (lease?.rentFrequency ?? lease?.RentFrequency) || 'Monthly',
    rentDueDay: lease?.rentDueDay ?? lease?.RentDueDay,
    isProvisionsAttachmentsComplete: true,
    includeEarlyTerminationClause: includeEarlyTerminationClause,
    earlyTerminationClauseText: includeEarlyTerminationClause ? earlyTerminationClauseText : null,
    additionalTerms: additionalTerms?.trim() || null,
    builtBefore1978: builtBefore1978,
    awareOfLeadPaint: awareOfLeadPaint,
    leadPaintExplanation: awareOfLeadPaint ? leadPaintExplanation?.trim() || null : null,
    hasLeadPaintRecords: hasLeadPaintRecords,
    leadPaintRecordsExplanation: hasLeadPaintRecords ? leadPaintRecordsExplanation?.trim() || null : null,
    isLeaseSpecificsComplete: lease?.isLeaseSpecificsComplete ?? lease?.IsLeaseSpecificsComplete,
    isRentDepositFeesComplete: lease?.isRentDepositFeesComplete ?? lease?.IsRentDepositFeesComplete,
    isPeopleOnLeaseComplete: lease?.isPeopleOnLeaseComplete ?? lease?.IsPeopleOnLeaseComplete,
    isPetsSmokingOtherComplete: lease?.isPetsSmokingOtherComplete ?? lease?.IsPetsSmokingOtherComplete,
    isUtilitiesMaintenanceKeysComplete: lease?.isUtilitiesMaintenanceKeysComplete ?? lease?.IsUtilitiesMaintenanceKeysComplete
  });

  const validateLeadPaint = () => {
    let valid = true;
    setLeadPaintExplanationError('');
    setLeadPaintRecordsExplanationError('');
    if (awareOfLeadPaint === true && !leadPaintExplanation?.trim()) {
      setLeadPaintExplanationError('This value is required.');
      valid = false;
    }
    if (hasLeadPaintRecords === true && !leadPaintRecordsExplanation?.trim()) {
      setLeadPaintRecordsExplanationError('This value is required.');
      valid = false;
    }
    return valid;
  };

  const handleSaveDraft = async () => {
    if (!leaseId || !lease) return;
    const currentLeaseId = lease?.id ?? lease?.Id ?? leaseId;
    try {
      await dispatch(updateLease(buildUpdatePayload(currentLeaseId)));
      await dispatch(updateLeaseAgreement(currentLeaseId, { isProvisionsAttachmentsComplete: true }));
      await propertiesRefetch();
      openSnackbar({ open: true, message: 'Draft saved successfully', variant: 'alert', alert: { color: 'success' } });
      if (embedded) {
        onSaved?.();
      } else {
        navigate(`/landlord/leases/build-lease-agreement?leaseId=${leaseId}&propertyId=${propertyId}${unitId ? `&unitId=${unitId}` : ''}`);
      }
    } catch (e) {
      console.error('Error saving draft:', e);
      openSnackbar({ open: true, message: e?.message || 'Failed to save draft', variant: 'alert', alert: { color: 'error' } });
    }
  };

  const handleSaveAndNext = async () => {
    if (!leaseId || !lease) return;
    if (!validateLeadPaint()) return;
    const currentLeaseId = lease?.id ?? lease?.Id ?? leaseId;
    setSaving(true);
    try {
      const result = await dispatch(updateLease(buildUpdatePayload(currentLeaseId)));
      if (result?.success) await dispatch(updateLeaseAgreement(currentLeaseId, { isProvisionsAttachmentsComplete: true }));
      if (result?.success) {
        await propertiesRefetch();
        openSnackbar({ open: true, message: 'Saved successfully', variant: 'alert', alert: { color: 'success' } });
        if (embedded) {
          onSaved?.();
        } else {
          navigate(`/landlord/leases/build-lease-agreement?leaseId=${leaseId}&propertyId=${propertyId}${unitId ? `&unitId=${unitId}` : ''}`);
        }
      } else {
        openSnackbar({ open: true, message: result?.message || 'Failed to save', variant: 'alert', alert: { color: 'error' } });
      }
    } catch (e) {
      console.error('Error saving:', e);
      openSnackbar({ open: true, message: e?.response?.data?.message || e?.message || 'Failed to save', variant: 'alert', alert: { color: 'error' } });
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '100vh' }}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Box sx={embedded ? { bgcolor: 'transparent' } : { minHeight: '100vh', bgcolor: 'background.default', display: 'flex', justifyContent: 'center' }}>
      <Container maxWidth={embedded ? false : "md"} disableGutters={embedded} sx={{ py: embedded ? 0 : 3 }}>
        {!embedded && <BuildLeaseAgreementHeader onBack={handleBack} onSaveDraft={handleSaveDraft} showTitle={false} />}
        <MainCard>
          <Stack spacing={4}>
            {!embedded && (
              <>
                <Box>
                  <Typography variant="h4" fontWeight={700} sx={{ mb: 1 }}>
                    Provisions & Attachments
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Add custom clauses, lead-based paint disclosure, and attachments to your lease agreement.
                  </Typography>
                </Box>
                <Divider />
              </>
            )}

            {/* Early Termination */}
            <Box>
              <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 2 }}>
                <FileTextOutlined style={{ fontSize: 24, color: theme.palette.primary.main }} />
                <Typography variant="h5" fontWeight={600}>
                  Early Termination
                </Typography>
              </Stack>
              <FormControl component="fieldset">
                <FormLabel sx={{ mb: 0.5 }}>Would you like to include an early termination clause?</FormLabel>
                <Typography variant="body2" color="text.secondary" sx={{ mb: 1.5 }}>
                  Early termination clauses allow you and/or the tenant to terminate the lease ahead of the scheduled end date.
                </Typography>
                <RadioGroup
                  row
                  value={includeEarlyTerminationClause ? 'yes' : 'no'}
                  onChange={(e) => setIncludeEarlyTerminationClause(e.target.value === 'yes')}
                >
                  <FormControlLabel value="yes" control={<Radio />} label="Yes" />
                  <FormControlLabel value="no" control={<Radio />} label="No" />
                </RadioGroup>
              </FormControl>
              {includeEarlyTerminationClause && (
                <Box sx={{ mt: 3 }}>
                  <Typography variant="subtitle1" fontWeight={600} sx={{ mb: 1 }}>
                    Customize Early Termination Clause
                  </Typography>
                  <TextField
                    fullWidth
                    multiline
                    rows={6}
                    value={earlyTerminationClauseText}
                    onChange={(e) => setEarlyTerminationClauseText(e.target.value.slice(0, 2000))}
                    inputProps={{ maxLength: 2000 }}
                    helperText={`${earlyTerminationClauseText.length} / 2000 characters used`}
                    size="small"
                    sx={{
                      '& .MuiOutlinedInput-root': { bgcolor: alpha(theme.palette.primary.main, 0.02) }
                    }}
                  />
                </Box>
              )}
            </Box>
            <Divider />

            {/* Additional Terms */}
            <Box>
              <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 2 }}>
                <BookOutlined style={{ fontSize: 24, color: theme.palette.primary.main }} />
                <Typography variant="h5" fontWeight={600}>
                  Additional terms
                </Typography>
              </Stack>
              <FormLabel sx={{ mb: 0.5 }}>Are there any additional terms you&apos;d like to add to this agreement?</FormLabel>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                This is where you can add custom clauses, rules, or provisions specific to your property and/or local area. Language added here will
                supersede any conflicting provisions within the lease agreement.
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 1.5 }}>
                If you&apos;d prefer to avoid conflicting provisions or make further customizations, use our Advanced Editor after all sections of the
                Builder are complete. If you add additional terms here or use the advanced editor, you may consider speaking with a local lawyer to
                ensure compliance.
              </Typography>
              <TextField
                fullWidth
                multiline
                rows={6}
                value={additionalTerms}
                onChange={(e) => setAdditionalTerms(e.target.value.slice(0, 10000))}
                placeholder="Additional Terms (Optional)"
                inputProps={{ maxLength: 10000 }}
                helperText={`${additionalTerms.length} / 10,000 characters used`}
                size="small"
                sx={{
                  '& .MuiOutlinedInput-root': { bgcolor: alpha(theme.palette.primary.main, 0.02) }
                }}
              />
            </Box>
            <Divider />

            {/* Lead-based Paint Disclosure */}
            <Box>
              <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 2 }}>
                <BgColorsOutlined style={{ fontSize: 24, color: theme.palette.primary.main }} />
                <Typography variant="h5" fontWeight={600}>
                  Lead-based Paint Disclosure
                </Typography>
              </Stack>
              <FormControl component="fieldset" fullWidth sx={{ mb: 2 }}>
                <FormLabel sx={{ mb: 0.5 }}>Was this property built prior to January 1st, 1978?</FormLabel>
                <RadioGroup
                  row
                  value={builtBefore1978 === true ? 'yes' : builtBefore1978 === false ? 'no' : ''}
                  onChange={(e) => setBuiltBefore1978(e.target.value === 'yes')}
                >
                  <FormControlLabel value="yes" control={<Radio />} label="Yes" />
                  <FormControlLabel value="no" control={<Radio />} label="No" />
                </RadioGroup>
              </FormControl>
              {builtBefore1978 === true && (
                <Box
                  sx={{
                    p: 2,
                    mb: 2,
                    borderRadius: 2,
                    bgcolor: alpha(theme.palette.info.main, 0.06),
                    border: `1px solid ${alpha(theme.palette.info.main, 0.2)}`
                  }}
                >
                  <Stack direction="row" spacing={1} alignItems="flex-start">
                    <InfoCircleOutlined style={{ fontSize: 18, color: theme.palette.info.main, marginTop: 2 }} />
                    <Box>
                      <Typography variant="subtitle2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                        Federal Pamphlet
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        {FEDERAL_LEAD_PAMPHLET_TEXT}
                      </Typography>
                    </Box>
                  </Stack>
                </Box>
              )}

              <FormControl component="fieldset" fullWidth sx={{ mb: 2 }}>
                <FormLabel sx={{ mb: 0.5 }}>
                  Are you aware of lead-based paint and/or lead-based paint hazards present in the housing?
                </FormLabel>
                <RadioGroup
                  row
                  value={awareOfLeadPaint === true ? 'yes' : awareOfLeadPaint === false ? 'no' : ''}
                  onChange={(e) => {
                    setAwareOfLeadPaint(e.target.value === 'yes');
                    if (e.target.value === 'no') setLeadPaintExplanationError('');
                  }}
                >
                  <FormControlLabel value="yes" control={<Radio />} label="Yes" />
                  <FormControlLabel value="no" control={<Radio />} label="No" />
                </RadioGroup>
              </FormControl>
              {awareOfLeadPaint === true && (
                <TextField
                  fullWidth
                  multiline
                  rows={3}
                  value={leadPaintExplanation}
                  onChange={(e) => {
                    setLeadPaintExplanation(e.target.value);
                    if (leadPaintExplanationError) setLeadPaintExplanationError('');
                  }}
                  label="PLEASE EXPLAIN"
                  required
                  error={!!leadPaintExplanationError}
                  helperText={leadPaintExplanationError}
                  size="small"
                  sx={{ mb: 2, '& .MuiOutlinedInput-root': {  } }}
                />
              )}

              <FormControl component="fieldset" fullWidth sx={{ mb: 0.5 }}>
                <FormLabel sx={{ mb: 0.5 }}>
                  Do you have any records or reports regarding lead-based paint, pertaining to the housing?
                </FormLabel>
                <RadioGroup
                  row
                  value={hasLeadPaintRecords === true ? 'yes' : hasLeadPaintRecords === false ? 'no' : ''}
                  onChange={(e) => {
                    setHasLeadPaintRecords(e.target.value === 'yes');
                    if (e.target.value === 'no') setLeadPaintRecordsExplanationError('');
                  }}
                >
                  <FormControlLabel value="yes" control={<Radio />} label="Yes" />
                  <FormControlLabel value="no" control={<Radio />} label="No" />
                </RadioGroup>
              </FormControl>
              {hasLeadPaintRecords === true && (
                <Box sx={{ mb: 2 }}>
                  <Typography variant="body2" color="text.secondary" fontStyle="italic" sx={{ mb: 1 }}>
                    {LEAD_PAINT_RECORDS_GUIDANCE}
                  </Typography>
                  <TextField
                    fullWidth
                    multiline
                    rows={3}
                    value={leadPaintRecordsExplanation}
                    onChange={(e) => {
                      setLeadPaintRecordsExplanation(e.target.value);
                      if (leadPaintRecordsExplanationError) setLeadPaintRecordsExplanationError('');
                    }}
                    label="PLEASE EXPLAIN"
                    required
                    error={!!leadPaintRecordsExplanationError}
                    helperText={leadPaintRecordsExplanationError}
                    size="small"
                    sx={{ '& .MuiOutlinedInput-root': {  } }}
                  />
                </Box>
              )}
            </Box>
            <Divider />

            {/* Attachments */}
            <Box>
              <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 2 }}>
                <FolderOpenOutlined style={{ fontSize: 24, color: theme.palette.primary.main }} />
                <Typography variant="h5" fontWeight={600}>
                  Attachments
                </Typography>
              </Stack>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                Attachments are added to the end of your lease agreement and will be arranged by the order they are uploaded. If applicable,
                attachments can be signed electronically along with the lease.
              </Typography>
              <Box
                sx={{
                  p: 2,
                  mb: 2,
                  borderRadius: 2,
                  bgcolor: alpha(theme.palette.info.main, 0.06),
                  border: `1px solid ${alpha(theme.palette.info.main, 0.2)}`
                }}
              >
                <Stack direction="row" spacing={1} alignItems="flex-start">
                  <InfoCircleOutlined style={{ fontSize: 18, color: theme.palette.info.main, marginTop: 2 }} />
                  <Box>
                    <Typography variant="subtitle2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                      Property Condition Reports
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      {PROPERTY_CONDITION_REPORTS_TEXT}
                    </Typography>
                  </Box>
                </Stack>
              </Box>
              <Box
                sx={{
                  py: 4,
                  px: 2,
                  border: `2px dashed ${theme.palette.divider}`,
                  borderRadius: 2,
                  textAlign: 'center',
                  bgcolor: alpha(theme.palette.primary.main, 0.02)
                }}
              >
                <CloudUploadOutlined style={{ fontSize: 48, color: theme.palette.text.secondary, marginBottom: 8 }} />
                <Typography variant="body2" color="text.secondary">
                  CLICK OR DRAG TO UPLOAD
                </Typography>
                <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1 }}>
                  File upload coming soon.
                </Typography>
              </Box>
            </Box>

            <Stack direction="row" spacing={2} justifyContent="flex-end" sx={{ pt: 2 }}>
              <Button variant="outlined" onClick={handleSaveDraft} disabled={saving} sx={{ textTransform: 'none' }}>
                Save
              </Button>
              <Button variant="contained" onClick={handleSaveAndNext} disabled={saving} sx={{ textTransform: 'none' }}>
                {saving ? <CircularProgress size={24} /> : 'Save & Next'}
              </Button>
            </Stack>
          </Stack>
        </MainCard>
      </Container>
    </Box>
  );
}
