export const DASHBOARD_ACTION_TYPES = {
  GET_DASHBOARD_SUMMARY_START: 'dashboard/GET_DASHBOARD_SUMMARY_START',
  GET_DASHBOARD_SUMMARY_SUCCESS: 'dashboard/GET_DASHBOARD_SUMMARY_SUCCESS',
  GET_DASHBOARD_SUMMARY_FAILED: 'dashboard/GET_DASHBOARD_SUMMARY_FAILED'
};
