export const LISTING_ACTION_TYPES = {
  GET_LISTINGS_START: 'listing/GET_LISTINGS_START',
  GET_LISTINGS_SUCCESS: 'listing/GET_LISTINGS_SUCCESS',
  GET_LISTINGS_FAILED: 'listing/GET_LISTINGS_FAILED',
  
  GET_LISTING_START: 'listing/GET_LISTING_START',
  GET_LISTING_SUCCESS: 'listing/GET_LISTING_SUCCESS',
  GET_LISTING_FAILED: 'listing/GET_LISTING_FAILED',
  
  CREATE_LISTING_START: 'listing/CREATE_LISTING_START',
  CREATE_LISTING_SUCCESS: 'listing/CREATE_LISTING_SUCCESS',
  CREATE_LISTING_FAILED: 'listing/CREATE_LISTING_FAILED',
  
  UPDATE_LISTING_START: 'listing/UPDATE_LISTING_START',
  UPDATE_LISTING_SUCCESS: 'listing/UPDATE_LISTING_SUCCESS',
  UPDATE_LISTING_FAILED: 'listing/UPDATE_LISTING_FAILED',
  
  DELETE_LISTING_START: 'listing/DELETE_LISTING_START',
  DELETE_LISTING_SUCCESS: 'listing/DELETE_LISTING_SUCCESS',
  DELETE_LISTING_FAILED: 'listing/DELETE_LISTING_FAILED',
  
  SET_SELECTED_LISTING: 'listing/SET_SELECTED_LISTING',
  CLEAR_SELECTED_LISTING: 'listing/CLEAR_SELECTED_LISTING',
};
