export const TENANT_ACTION_TYPES = {
  SET_SELECTED_TENANT: 'tenant/SET_SELECTED_TENANT',
  SET_TENANT_FIELD: 'tenant/SET_TENANT_FIELD',
  ADD_UPDATE_TENANT_SUCCESS: 'tenant/ADD_UPDATE_TENANT_SUCCESS',
  ADD_UPDATE_TENANT_FAILED: 'tenant/ADD_UPDATE_TENANT_FAILED',
  UPDATE_TENANT_SUCCESS: 'tenant/UPDATE_TENANT_SUCCESS',
  UPDATE_TENANT_FAILED: 'tenant/UPDATE_TENANT_FAILED',
  UPDATE_TENANT_FIELD: 'tenant/UPDATE_TENANT_FIELD',
  DELETE_TENANT_SUCCESS: 'tenant/DELETE_TENANT_SUCCESS',
  GET_TENANTS_START: 'tenant/GET_TENANTS_START',
  GET_TENANTS_SUCCESS: 'tenant/GET_TENANTS_SUCCESS',
  GET_TENANTS_FAILED: 'tenant/GET_TENANTS_FAILED',
  GET_ALL_TENANTS_SUCCESS: 'tenant/GET_ALL_TENANTS_SUCCESS',
  GET_ALL_TENANTS_FAILED: 'tenant/GET_ALL_TENANTS_FAILED',
  GET_TENANT_SUCCESS: 'tenant/GET_TENANT_SUCCESS',
  GET_TENANT_FAILED: 'tenant/GET_TENANT_FAILED',
  DELETE_TENANT_FAILED: 'tenant/DELETE_TENANT_FAILED',
  RESET_STATE: 'tenant/RESET_STATE'
};
