export const PAYMENT_ACTION_TYPES = {
  GET_PAYMENTS_SUCCESS: 'payment/GET_PAYMENTS_SUCCESS',
  GET_PAYMENTS_FAILURE: 'payment/GET_PAYMENTS_FAILURE',
  ADD_PAYMENT_FAILURE: 'payment/ADD_PAYMENT_FAILURE',
  ADD_PAYMENT_SUCCESS: 'payment/ADD_PAYMENT_SUCCESS',
  GET_ALL_PAYMENTS_SUCCESS: 'payment/GET_ALL_PAYMENTS_SUCCESS',
  GET_ALL_PAYMENTS_FAILURE: 'payment/GET_ALL_PAYMENTS_FAILURE'
};
