export const RECURRING_EXPENSE_ACTION_TYPES = {
  // GET operations
  GET_RECURRING_EXPENSES_START: 'recurring-expense/GET_RECURRING_EXPENSES_START',
  GET_RECURRING_EXPENSES_SUCCESS: 'recurring-expense/GET_RECURRING_EXPENSES_SUCCESS',
  GET_RECURRING_EXPENSES_FAILURE: 'recurring-expense/GET_RECURRING_EXPENSES_FAILURE',
  
  GET_RECURRING_EXPENSE_BY_ID_START: 'recurring-expense/GET_RECURRING_EXPENSE_BY_ID_START',
  GET_RECURRING_EXPENSE_BY_ID_SUCCESS: 'recurring-expense/GET_RECURRING_EXPENSE_BY_ID_SUCCESS',
  GET_RECURRING_EXPENSE_BY_ID_FAILURE: 'recurring-expense/GET_RECURRING_EXPENSE_BY_ID_FAILURE',
  
  // ADD operations
  ADD_RECURRING_EXPENSE_START: 'recurring-expense/ADD_RECURRING_EXPENSE_START',
  ADD_RECURRING_EXPENSE_SUCCESS: 'recurring-expense/ADD_RECURRING_EXPENSE_SUCCESS',
  ADD_RECURRING_EXPENSE_FAILURE: 'recurring-expense/ADD_RECURRING_EXPENSE_FAILURE',
  
  // UPDATE operations
  UPDATE_RECURRING_EXPENSE_START: 'recurring-expense/UPDATE_RECURRING_EXPENSE_START',
  UPDATE_RECURRING_EXPENSE_SUCCESS: 'recurring-expense/UPDATE_RECURRING_EXPENSE_SUCCESS',
  UPDATE_RECURRING_EXPENSE_FAILURE: 'recurring-expense/UPDATE_RECURRING_EXPENSE_FAILURE',
  
  // DELETE operations
  DELETE_RECURRING_EXPENSE_START: 'recurring-expense/DELETE_RECURRING_EXPENSE_START',
  DELETE_RECURRING_EXPENSE_SUCCESS: 'recurring-expense/DELETE_RECURRING_EXPENSE_SUCCESS',
  DELETE_RECURRING_EXPENSE_FAILURE: 'recurring-expense/DELETE_RECURRING_EXPENSE_FAILURE',
  
  // PAUSE/RESUME operations
  PAUSE_RECURRING_EXPENSE_START: 'recurring-expense/PAUSE_RECURRING_EXPENSE_START',
  PAUSE_RECURRING_EXPENSE_SUCCESS: 'recurring-expense/PAUSE_RECURRING_EXPENSE_SUCCESS',
  PAUSE_RECURRING_EXPENSE_FAILURE: 'recurring-expense/PAUSE_RECURRING_EXPENSE_FAILURE',
  
  RESUME_RECURRING_EXPENSE_START: 'recurring-expense/RESUME_RECURRING_EXPENSE_START',
  RESUME_RECURRING_EXPENSE_SUCCESS: 'recurring-expense/RESUME_RECURRING_EXPENSE_SUCCESS',
  RESUME_RECURRING_EXPENSE_FAILURE: 'recurring-expense/RESUME_RECURRING_EXPENSE_FAILURE',
  
  // State management
  SET_SELECTED_RECURRING_EXPENSE: 'recurring-expense/SET_SELECTED_RECURRING_EXPENSE',
  SET_RECURRING_EXPENSE_FIELD: 'recurring-expense/SET_RECURRING_EXPENSE_FIELD',
  RESET_RECURRING_EXPENSE_STATE: 'recurring-expense/RESET_RECURRING_EXPENSE_STATE'
};
