export const FUTURE_EXPENSE_ACTION_TYPES = {
  GET_FUTURE_EXPENSES_START: 'future-expense/GET_FUTURE_EXPENSES_START',
  GET_FUTURE_EXPENSES_SUCCESS: 'future-expense/GET_FUTURE_EXPENSES_SUCCESS',
  GET_FUTURE_EXPENSES_FAILURE: 'future-expense/GET_FUTURE_EXPENSES_FAILURE',
  ADD_FUTURE_EXPENSE_START: 'future-expense/ADD_FUTURE_EXPENSE_START',
  ADD_FUTURE_EXPENSE_SUCCESS: 'future-expense/ADD_FUTURE_EXPENSE_SUCCESS',
  ADD_FUTURE_EXPENSE_FAILURE: 'future-expense/ADD_FUTURE_EXPENSE_FAILURE',
  DELETE_FUTURE_EXPENSE_START: 'future-expense/DELETE_FUTURE_EXPENSE_START',
  DELETE_FUTURE_EXPENSE_SUCCESS: 'future-expense/DELETE_FUTURE_EXPENSE_SUCCESS',
  DELETE_FUTURE_EXPENSE_FAILURE: 'future-expense/DELETE_FUTURE_EXPENSE_FAILURE',
  MARK_FUTURE_EXPENSE_CLEANUP_PENDING: 'future-expense/MARK_FUTURE_EXPENSE_CLEANUP_PENDING',
  CLEAR_FUTURE_EXPENSE_CLEANUP_PENDING: 'future-expense/CLEAR_FUTURE_EXPENSE_CLEANUP_PENDING',
  HYDRATE_FUTURE_EXPENSE_CLEANUP: 'future-expense/HYDRATE_FUTURE_EXPENSE_CLEANUP'
};
