export const HOUSEHOLD_ACTION_TYPES = {
  GET_HOUSEHOLDS_START: 'household/GET_HOUSEHOLDS_START',
  GET_HOUSEHOLDS_SUCCESS: 'household/GET_HOUSEHOLDS_SUCCESS',
  GET_HOUSEHOLDS_FAILED: 'household/GET_HOUSEHOLDS_FAILED',
  UPDATE_HOUSEHOLD_START: 'household/UPDATE_HOUSEHOLD_START',
  UPDATE_HOUSEHOLD_SUCCESS: 'household/UPDATE_HOUSEHOLD_SUCCESS',
  UPDATE_HOUSEHOLD_FAILED: 'household/UPDATE_HOUSEHOLD_FAILED',
  SET_SELECTED_HOUSEHOLD: 'household/SET_SELECTED_HOUSEHOLD'
};
