import type { Metadata } from "next";
import FeatureLandingPage from "@/components/Marketing/FeatureLandingPage";
import { FiClipboard } from "react-icons/fi";
import { applyOttoSeo } from '@/lib/otto-seo';

export const metadata: Metadata = applyOttoSeo('/lease/online-condition-reports/', {
  title: "Online Move-In Condition Reports | Property Peace",
  description: "Document rental condition at move-in and move-out with online reports, photos, notes, and tenant-friendly records.",
  keywords: "online condition reports, move-in condition report, move-out inspection report, rental property inspection software",
  alternates: { canonical: "/lease/online-condition-reports" },
  openGraph: { title: "Online Move-In Condition Reports | Property Peace", description: "Document rental condition at move-in and move-out with online reports, photos, notes, and tenant-friendly records.", type: "website", url: "/lease/online-condition-reports" },
  twitter: { card: "summary_large_image", title: "Online Move-In Condition Reports | Property Peace", description: "Document rental condition at move-in and move-out with online reports, photos, notes, and tenant-friendly records." },
});

export default function Page() {
  return <FeatureLandingPage icon={FiClipboard} {...page} />;
}

const page = {'canonicalPath': '/lease/online-condition-reports', 'categoryLabel': 'Lease Management', 'categoryHref': '/features/lease-management', 'eyebrow': 'Lease documentation feature', 'title': 'Online Condition Reports for Move-In and Move-Out', 'subtitle': 'Create a clearer record of property condition with online reports, photos, room-by-room notes, and move-out documentation.', 'primaryCta': 'Document Condition Free', 'trustItems': ['No credit card required', 'Free for up to 5 units', 'Built for 1–50 units'], 'problemTitle': 'Deposit disputes often start with weak documentation', 'problemPoints': ['Move-in notes get lost or never collected consistently.', 'Photos are stored separately from the actual inspection record.', 'Move-out damage conversations are harder without a room-by-room baseline.'], 'solutionTitle': 'Create a cleaner condition record from day one', 'solutionPoints': ['Document rooms, fixtures, photos, and notes in a structured report.', 'Keep move-in and move-out records connected to the lease.', 'Use organized documentation when reviewing damage, repairs, or deposits.'], 'steps': [{'title': 'Walk the property', 'body': 'Capture room-by-room condition with notes and photos.'}, {'title': 'Store the report', 'body': 'Keep the condition record connected to the lease and tenant.'}, {'title': 'Compare at move-out', 'body': 'Use the baseline when reviewing repairs, cleaning, or deductions.'}], 'featureTitle': 'Condition report features', 'features': ['Move-in condition report workflow', 'Move-out inspection documentation', 'Photo and note capture', 'Room-by-room organization', 'Lease-linked storage', 'Exportable condition records'], 'outcomeTitle': 'Better documentation protects everyone', 'outcomes': ['Reduce unclear move-out conversations.', 'Keep a fair record for tenants and landlords.', 'Make repair decisions with better evidence.', 'Avoid hunting for photos when deposit questions come up.'], 'related': [{'label': 'Lease management', 'href': '/features/lease-management', 'description': 'Keep condition reports with lease records.'}, {'label': 'Document management', 'href': '/features/document-management', 'description': 'Store inspection files, leases, and receipts.'}, {'label': 'Move-in checklist article', 'href': '/blog/landlord-move-in-move-out-checklist', 'description': 'Use a checklist for smoother turnovers.'}], 'faqs': [{'question': 'Can I add photos to a condition report?', 'answer': 'Yes. Photos and notes can be stored with the report to create clearer documentation.'}, {'question': 'Is this useful for move-out inspections?', 'answer': 'Yes. A move-in baseline makes move-out review much clearer.'}, {'question': 'Can tenants receive a copy?', 'answer': 'Condition reports are intended to create organized records that can be shared or exported when needed.'}]};
