import type { Metadata } from "next";
import FeatureLandingPage from "@/components/Marketing/FeatureLandingPage";
import { FiBarChart2 } from "react-icons/fi";
import { applyOttoSeo } from '@/lib/otto-seo';

export const metadata: Metadata = applyOttoSeo('/rent/accounting/', {
  title: "Landlord Accounting Software | Property Peace",
  description: "Simple landlord accounting for ledgers, expenses, financial statements, payables, bank reconciliation, and tax-ready reports.",
  keywords: "landlord accounting software, rental property accounting, property financial statements, bank reconciliation for landlords",
  alternates: { canonical: "/rent/accounting" },
  openGraph: { title: "Landlord Accounting Software | Property Peace", description: "Simple landlord accounting for ledgers, expenses, financial statements, payables, bank reconciliation, and tax-ready reports.", type: "website", url: "/rent/accounting" },
  twitter: { card: "summary_large_image", title: "Landlord Accounting Software | Property Peace", description: "Simple landlord accounting for ledgers, expenses, financial statements, payables, bank reconciliation, and tax-ready reports." },
});

export default function Page() {
  return <FeatureLandingPage icon={FiBarChart2} {...page} />;
}

const page = {'canonicalPath': '/rent/accounting', 'categoryLabel': 'Rent & Accounting', 'categoryHref': '/features/financial-reports', 'eyebrow': 'Accounting feature', 'title': 'Landlord Accounting Without Enterprise Bloat', 'subtitle': 'Track income, expenses, ledgers, payables, and financial statements in the same system you use to manage rentals.', 'primaryCta': 'Organize Finances Free', 'trustItems': ['No credit card required', 'Free for up to 2 units', 'Built for 1–50 units'], 'problemTitle': 'Rental books get complicated when tools are split', 'problemPoints': ['Income lives in one place, expenses in another, and receipts somewhere else.', 'Property-level profitability is hard to see without extra spreadsheet work.', 'Tax prep becomes a scramble when categories and statements are incomplete.'], 'solutionTitle': 'One accounting workflow for small landlords', 'solutionPoints': ['Keep income, expenses, ledgers, and statements connected to each property.', 'Reconcile records and review profitability without jumping between tools.', 'Export cleaner reports for taxes, owners, or accountants.'], 'steps': [{'title': 'Track transactions', 'body': 'Record rent income, bills, expenses, and payables by account.'}, {'title': 'Review statements', 'body': 'Generate useful views like P&L, cash flow, and balances.'}, {'title': 'Reconcile and export', 'body': 'Match bank activity and prepare tax-ready reports.'}], 'featureTitle': 'Accounting functions included', 'features': ['Ledger and transaction history', 'Expense categorization', 'Profit & Loss and cash-flow reporting', 'Accounts payable tracking', 'Bank reconciliation support', 'Chart of accounts organization'], 'outcomeTitle': 'Understand each property financially', 'outcomes': ['See rental profitability without rebuilding reports by hand.', 'Keep tax categories cleaner throughout the year.', 'Know what you owe vendors and when payments are due.', 'Give your accountant better organized data.'], 'related': [{'label': 'Expense tracking', 'href': '/rent/expense-tracking', 'description': 'Capture receipts and repair costs as they happen.'}, {'label': 'Financial reporting', 'href': '/features/financial-reports', 'description': 'See profitability and portfolio performance.'}, {'label': 'Rent collection', 'href': '/features/rent-collection', 'description': 'Keep income records connected to payments.'}], 'faqs': [{'question': 'Can I track accounting by property?', 'answer': 'Yes. Property Peace is built around property-level records so income and expenses stay connected to the right rental.'}, {'question': 'Does it include financial statements?', 'answer': 'Yes. The accounting workflow supports landlord-friendly statements and reports such as P&L and cash-flow views.'}, {'question': 'Can I export data for taxes?', 'answer': 'Yes. Reports and exports help you prepare cleaner information for tax filing and accountant review.'}]};
